/* FLYRA UI — everything stays on this device. */
(() => {
'use strict';
const F=window.Flyra,$=id=>document.getElementById(id),art=$('artboard'),overlay=$('overlay');
let selectedPart='frame';
let project=F.makeProject(),selected=null,images=new Map(),undoStack=[],redoStack=[],zoom=1,guides=false,drag=null,saveTimer,toastTimer,renderQueued=false,filter='all',materialSeed=501,db=null,saving=Promise.resolve(),customAssets=[],assetSelection=new Set();
const MAX_LAYERS=150,historyLimit=40;
const seed=()=>Math.floor(Math.random()*2147483647);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3400);}
let previewProject=null;
let fontLoadRevision=0;
function loadProjectFonts(){const rev=++fontLoadRevision;F.ensureProjectFonts(project).then(()=>{if(rev===fontLoadRevision){draw();const status=$('fontStatus');if(status)status.textContent='書体を読み込み済み · 900超は輪郭を太らせて表現';}}).catch(()=>{if(rev===fontLoadRevision){const status=$('fontStatus');if(status)status.textContent='書体を読み込めません。ネット接続を確認して再読み込みしてください。';toast('オンライン書体を読み込めません。標準書体で一時表示しています。');}});}
function current(){return project.layers.find(o=>o.id===selected);}
function snapshot(){const copy=F.clone({...project,layers:project.layers.map(({src,...o})=>o)});project.layers.forEach((o,i)=>{if(o.src)copy.layers[i].src=o.src;});return copy;}
function sameState(a,b){if(a===b)return true;if(!a||!b||typeof a!=='object'||typeof b!=='object')return false;const keys=Object.keys(a),other=Object.keys(b);return keys.length===other.length&&keys.every(k=>Object.hasOwn(b,k)&&sameState(a[k],b[k]));}
function trimHistory(){while(undoStack.length>historyLimit)undoStack.shift();}
function pushHistory(){undoStack.push(snapshot());trimHistory();redoStack=[];}
function commit(action,{refresh=true}={}){finishAdjustment();const priorRedo=redoStack;pushHistory();try{action();}catch(e){project=undoStack.pop();redoStack=priorRedo;sync();toast(e.message||'変更できませんでした');return;}if(sameState(undoStack.at(-1),project)){undoStack.pop();redoStack=priorRedo;}scheduleSave();if(refresh)sync();else{draw();updateUndo();}}
function scheduleSave(){clearTimeout(saveTimer);$('saveStatus').textContent='保存中…';saveTimer=setTimeout(()=>{const savedState=snapshot();saving=saving.then(()=>persist(savedState)).catch(()=>{$('saveStatus').textContent='自動保存できません · データ保存を利用';});},400);}
function persist(p){return new Promise((resolve,reject)=>{if(!db){try{localStorage.setItem('flyra-project-v1',JSON.stringify(p));$('saveStatus').textContent='この端末に保存済み';resolve();}catch(e){reject(e);}return;}const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(p,'current');tx.oncomplete=()=>{$('saveStatus').textContent='この端末に保存済み';resolve();};tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
async function initStorage(){try{db=await new Promise((resolve,reject)=>{const req=indexedDB.open('flyra-studio',2);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('projects'))req.result.createObjectStore('projects');if(!req.result.objectStoreNames.contains('assets'))req.result.createObjectStore('assets');};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});const stored=await new Promise((resolve,reject)=>{const req=db.transaction('projects').objectStore('projects').get('current');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});if(stored){project=F.validate(stored);images=await F.prepare(project);toast('前回のデザインを復元しました');}customAssets=await new Promise((resolve,reject)=>{const req=db.transaction('assets').objectStore('assets').get('library');req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error);});}catch(e){try{const stored=localStorage.getItem('flyra-project-v1');if(stored){project=F.validate(JSON.parse(stored));images=await F.prepare(project);}}catch(e2){toast('保存データを復元できませんでした。保存ファイルから開いてください。');}if(!db)$('saveStatus').textContent='このブラウザの保存機能は制限されています';}}
function updateUndo(){$('undo').disabled=!undoStack.length;$('redo').disabled=!redoStack.length;}
const pendingFields=new WeakSet();
document.addEventListener('input',e=>{if(e.target.matches('[data-prop],#projectName,[id^="content-"]'))pendingFields.add(e.target);},true);
document.addEventListener('change',e=>pendingFields.delete(e.target),true);
let historyQueue=Promise.resolve();
function history(direction){
 F.closeContextMenu?.();
 const field=document.activeElement;if(pendingFields.has(field)){pendingFields.delete(field);field.dispatchEvent(new Event('change',{bubbles:true}));}
 finishAdjustment();if(drag)endDrag();F.cancelLayerDrag?.();window.FlyraSelect.close();
 historyQueue=historyQueue.then(async()=>{const from=direction==='undo'?undoStack:redoStack,to=direction==='undo'?redoStack:undoStack;if(!from.length)return;to.push(snapshot());project=from.pop();images=await F.prepare(project);sync();scheduleSave();}).catch(()=>toast('履歴を復元できませんでした'));return historyQueue;
}
document.addEventListener('keydown',e=>{if(e.isComposing||!(e.ctrlKey||e.metaKey))return;const key=e.key.toLowerCase();if(key!=='z'&&key!=='y')return;e.preventDefault();e.stopImmediatePropagation();history(key==='y'||e.shiftKey?'redo':'undo');},true);
function fit(){const area=$('canvasArea'),pad=window.innerWidth<600?40:68;const scale=Math.min((area.offsetWidth-pad)/project.width,(area.offsetHeight-pad)/project.height)*zoom;const width=Math.max(40,project.width*scale),height=Math.max(40,project.height*scale);$('canvasWrap').style.width=width+'px';$('canvasWrap').style.height=height+'px';const dpr=Math.min(window.devicePixelRatio||1,2);renderWidth=Math.round(width*dpr);renderHeight=Math.round(height*dpr);draw();}
let renderWidth=art.width,renderHeight=art.height;const renderBuffer=document.createElement('canvas');
function draw(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(()=>{renderQueued=false;if(renderBuffer.width!==renderWidth)renderBuffer.width=renderWidth;if(renderBuffer.height!==renderHeight)renderBuffer.height=renderHeight;F.render(renderBuffer,previewProject||project,{images});if(art.width!==renderWidth)art.width=renderWidth;if(art.height!==renderHeight)art.height=renderHeight;const ctx=art.getContext('2d');ctx.clearRect(0,0,art.width,art.height);ctx.drawImage(renderBuffer,0,0);if(overlay.width!==renderWidth)overlay.width=renderWidth;if(overlay.height!==renderHeight)overlay.height=renderHeight;drawOverlay();});}
function drawOverlay(){
 const ctx=overlay.getContext('2d');ctx.clearRect(0,0,overlay.width,overlay.height);if(previewProject)return;
 const scale=overlay.width/project.width,u=project.width/art.getBoundingClientRect().width;
 ctx.save();ctx.scale(scale,scale);ctx.lineWidth=1.5*u;
 if(guides){ctx.strokeStyle='#28a07fc0';ctx.setLineDash([5*u,5*u]);ctx.strokeRect(project.width*.045,project.height*.045,project.width*.91,project.height*.91);ctx.setLineDash([]);}
 if(drag?.snapX||drag?.snapY){ctx.strokeStyle='#ec4899';ctx.setLineDash([5*u,4*u]);ctx.beginPath();if(drag.snapX){ctx.moveTo(project.width/2,0);ctx.lineTo(project.width/2,project.height);}if(drag.snapY){ctx.moveTo(0,project.height/2);ctx.lineTo(project.width,project.height/2);}ctx.stroke();ctx.setLineDash([]);}
 const o=current();if(o&&o.visible){for(const reflected of o.mirror?[false,true]:[false]){ctx.save();if(reflected){ctx.translate(project.width,0);ctx.scale(-1,1);}ctx.translate(o.x+o.w/2,o.y+o.h/2);ctx.rotate(o.rotation*Math.PI/180);ctx.translate(-o.w/2,-o.h/2);ctx.strokeStyle=o.locked?'#bb8a35':'#258a6e';ctx.strokeRect(0,0,o.w,o.h);if(!o.locked&&!(o.slot&&selectedPart==='image')){ctx.fillStyle='white';const size=8*u;for(const [x,y] of [[0,0],[o.w,0],[0,o.h],[o.w,o.h]]){ctx.fillRect(x-size/2,y-size/2,size,size);ctx.strokeRect(x-size/2,y-size/2,size,size);}const h=F.rotationHandle(o,u,project.width,project.height);ctx.beginPath();ctx.moveTo(o.w/2,0);ctx.lineTo(h.x,h.y);ctx.stroke();ctx.beginPath();ctx.arc(h.x,h.y,6*u,0,Math.PI*2);ctx.fill();ctx.stroke();}ctx.restore();}}ctx.restore();
}
function sync(){const kind=project.contentKind||F.contentKind(project.template);$('contentHeading').textContent=kind==='goods'?'グッズの告知内容':'ライブの告知内容';for(const [key,label] of Object.entries(F.contentLabels[kind]))document.querySelector('[data-content-label="'+key+'"]').textContent=label;window.FlyraSelect.close();loadProjectFonts();if(selected&&!current())selected=null;$('projectName').value=project.name;for(const key of Object.keys(F.defaultContent))$('content-'+key).value=project.content[key];const preset=`${project.width},${project.height}`;if([...$('sizePreset').options].some(o=>o.value===preset))$('sizePreset').value=preset;$('canvasInfo').textContent=`${project.width} × ${project.height} px`;$('layerCount').textContent=project.layers.length;updateUndo();renderLayers();renderProperties();renderFavorites();updateTemplateSelection();window.FlyraSelect.enhance();window.FlyraSelect.refresh();fit();}
function select(id,part='frame'){finishAdjustment();window.FlyraSelect.close();selected=id;selectedPart=part;renderLayers();renderProperties();window.FlyraSelect.enhance();drawOverlay();}
function renderTemplates(){const list=$('templateList');list.replaceChildren();for(const t of F.templates.filter(t=>filter==='all'||t.category===filter)){const button=document.createElement('button');button.className='template-card';button.dataset.template=t.id;button.setAttribute('aria-label',t.name+' テンプレート');const canvas=document.createElement('canvas');canvas.width=220;canvas.height=275;const p=F.makeProject(t.id,t.preview?{...(F.contentKind(t.id)==='goods'?F.goodsContent:F.defaultContent),...t.preview}:undefined);F.render(canvas,p);button.appendChild(canvas);const name=document.createElement('b');name.textContent=t.name;button.appendChild(name);const caption=document.createElement('small');caption.textContent=t.caption;button.appendChild(caption);button.addEventListener('click',()=>{commit(()=>{project=F.applyTemplate(project,t.id,seed());selected=null;});toast(t.name+' を適用しました');});list.appendChild(button);}updateTemplateSelection();}
function updateTemplateSelection(){document.querySelectorAll('.template-card').forEach(b=>{b.classList.toggle('selected',b.dataset.template===project.template);b.setAttribute('aria-pressed',String(b.dataset.template===project.template));b.querySelector('.card-check')?.remove();if(b.dataset.template===project.template){const check=document.createElement('span');check.className='card-check';check.textContent='✓';b.appendChild(check);}});}
function renderLayers(){const list=$('layerList');list.replaceChildren();for(const o of [...project.layers].reverse()){const row=document.createElement('div');row.dataset.layerId=o.id;row.draggable=!o.locked;row.title=o.locked?'ロックを解除すると並び替えできます':'ドラッグして並び替え';row.className='layer-row'+(o.id===selected&&!(o.slot&&o.type==='image'&&selectedPart==='image')?' selected':'')+(!o.visible?' hidden-layer':'');const icon=document.createElement('span');icon.className='layer-icon';icon.textContent=o.type==='text'?'T':o.type==='image'?'▧':['particles','grain','halftone'].includes(o.type)?'⁙':'◈';const name=document.createElement('button');name.className='layer-name';const label=o.slot?(o.frameName||(o.type==='image'?'写真フレーム':o.name)):o.name;name.textContent=label;name.title=label;name.setAttribute('aria-label','レイヤー '+label);name.onclick=()=>select(o.id);const vis=document.createElement('button');vis.className='layer-toggle';vis.textContent=o.visible?'◉':'○';vis.title=o.visible?'非表示にする':'表示する';vis.setAttribute('aria-label',o.name+'の'+vis.title);vis.onclick=()=>commit(()=>o.visible=!o.visible);const lock=document.createElement('button');lock.className='layer-toggle';lock.textContent=o.locked?'▣':'▫';lock.title=o.locked?'ロック解除':'ロックする';lock.setAttribute('aria-label',o.name+'を'+lock.title);lock.onclick=()=>commit(()=>o.locked=!o.locked);row.append(icon,name,vis,lock);list.appendChild(row);if(o.slot&&o.type==='image'){const child=document.createElement('div');child.className='layer-child'+(o.id===selected&&selectedPart==='image'?' selected':'');child.dataset.frameChild=o.id;const branch=document.createElement('span');branch.textContent='└ ▧';const button=document.createElement('button');button.className='layer-name';button.textContent=o.name;button.setAttribute('aria-label','枠内画像 '+o.name);button.onclick=()=>select(o.id,'image');child.append(branch,button);list.append(child);}}}
function input(label,key,value,type='number',attrs=''){if(type==='color'&&['color','color2','bgcolor','stickerColor'].includes(key)){const obj=key==='bgcolor'?project.background:current(),prop=key==='bgcolor'?'bgFinish':key+'Finish';return options(label+'の仕上げ',prop,obj?.[key==='bgcolor'?'colorFinish':prop]||'solid',F.finishes)+`<label>${label}<input data-prop="${key}" type="color" value="${esc(value)}" ${attrs}></label>`;}return `<label>${label}<input data-prop="${key}" type="${type}" value="${esc(value)}" ${attrs}></label>`;}
function options(label,key,value,entries){return `<label>${label}<select data-prop="${key}">${entries.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${t}</option>`).join('')}</select></label>`;}
function range(label,key,value,min,max,step=1){const factor=key==='opacity'?100:1;if(key==='rotation'&&(value<0||value>360))value=F.normalizeRotation(value);const v=Number((value*factor).toFixed(3)),attrs=`min="${min*factor}" max="${max*factor}" step="${step*factor}" data-scale="${factor}"`;return `<div class="range-control"><div class="range-heading"><span>${label}${key==='opacity'?' (%)':key==='rotation'?' (°)':''}</span><input aria-label="${label}の数値" data-prop="${key}" type="number" value="${v}" ${attrs}></div><input aria-label="${label}" data-prop="${key}" type="range" value="${v}" ${attrs}></div>`;}
let adjustment=null;
function finishAdjustment(){if(!adjustment)return;const before=adjustment;adjustment=null;if(!sameState(before,project)){undoStack.push(before);trimHistory();redoStack=[];}scheduleSave();updateUndo();}
function cancelAdjustment(){if(!adjustment)return;project=adjustment;adjustment=null;scheduleSave();sync();}

function renderProperties(){const o=current(),box=$('properties');const child=!!(o?.slot&&o.type==='image'&&selectedPart==='image'),frame=!!(o?.slot&&!child);$('selectionType').textContent=o?({text:'文字',image:'画像',gradient:'グラデーション',mesh:'メッシュ',grain:'グレイン',particles:'粒子',halftone:'網点'})[o.type]||'図形':'キャンバス';
 if(!o){box.innerHTML=`<div class="empty-selection">要素をクリックして選択。<br>色やサイズを、ここで調整できます。</div>${input('背景色','bgcolor',project.background.color,'color')}<div class="color-swatch-row">${F.palettes.map((p,i)=>`<button class="color-swatch" data-palette="${i}" aria-label="配色 ${i+1}" style="background:${p[2]}"></button>`).join('')}</div><button id="blankCanvas" class="wide">白紙からつくる ＋</button><p class="small-note">変更前のデザインには「元に戻す」で戻れます。</p>`;
 box.querySelector('[data-prop=bgFinish]').onchange=e=>commit(()=>{project.background.colorFinish=e.target.value;});box.querySelector('[data-prop=bgcolor]').onchange=e=>commit(()=>{project.background.type='solid';project.background.color=e.target.value;});box.querySelectorAll('[data-palette]').forEach(b=>b.onclick=()=>commit(()=>F.recolor(project,F.palettes[+b.dataset.palette])));$('blankCanvas').onclick=()=>commit(()=>{project.layers=[];project.background.type='solid';project.background.color='#ffffff';project.template='blank';});return;}
 let html=input(child?'画像名':frame?'枠の名前':'レイヤー名',frame&&o.type==='image'?'frameName':'name',frame&&o.type==='image'?(o.frameName||'写真フレーム'):o.name,'text','maxlength="200"');if(o.locked)html+='<p class="lock-notice">▣ ロック中です。編集するには下の鍵を解除。</p>';if(o.slot&&o.type!=='image')html+='<button id="replaceImage" class="primary wide">この形に写真を入れる</button><p class="small-note">枠の形で自動的に切り抜きます。枠への画像ドロップでも追加できます。</p>';
 if(o.stickerKind){$('selectionType').textContent='ステッカー';html+='<h3>ステッカーの色</h3>';html+=options('本体の色','stickerColorMode',o.stickerColorMode||'original',[['original','元の色'],['color','色を変更']]);html+=input('本体カラー','stickerColor',o.stickerColor||'#303030','color');html+='<p class="small-note">バーコード・罫線と紙の質感を残して本体を着色します。文字は「文字・図形」からテキストレイヤーで追加できます。</p>';if(F.stickerFields.some(([k])=>o[k]))html+='<label class="check-label"><input data-prop="stickerShowText" type="checkbox" '+(o.stickerShowText!==false?'checked':'')+'>以前の埋め込み文字を表示</label>';}
 if(o.type==='text'){html+=`<label>テキスト<textarea data-prop="text" rows="3" maxlength="1000">${esc(o.text)}</textarea></label>`;html+=options('書体','font',o.font,F.fontCatalog.map(f=>[f.id,f.label]));html+=`<div class="two-cols">${input('サイズ（上限）','fontSize',Math.round(o.fontSize),'number','min="1" max="2000"')}</div>`+range('太さ','fontWeight',o.fontWeight,100,2000,1);html+='<p id="fontStatus" class="small-note">追加書体は初回にオンラインで読み込みます。英字書体の日本語は標準書体で表示。</p>';html+=options('文字揃え','align',o.align,o.textShape==='vertical'?[['left','上揃え'],['center','中央'],['right','下揃え']]:[['left','左揃え'],['center','中央'],['right','右揃え']]);html+=range(o.textShape==='vertical'?'列の間隔':'行間','lineHeight',o.lineHeight,.7,3,.05);html+=`<div class="two-cols"><label class="check-label"><input data-prop="outline" type="checkbox" ${o.outline?'checked':''}>輪郭だけ</label><label class="check-label"><input data-prop="shadow" type="checkbox" ${o.shadow?'checked':''}>影をつける</label></div>`;if(F.supportsArc)html+=options('文字の並び','textShape',o.textShape||'normal',[['normal','通常'],['arc','アーチ / 円弧'],['vertical','縦書き']]);}
 if(o.type!=='image')html+=`<div class="two-cols">${input('カラー','color',o.color,'color')}${input(o.type==='text'?'影の色':'カラー B','color2',o.color2,'color')}</div>`;
 if(['gradient','mesh','particles','grain','halftone'].includes(o.type)){html+=range('角度','angle',o.angle||0,0,360);html+=range('密度','density',o.density||45,5,100);html+='<button id="reseedLayer" class="wide">↻ パターンを作り直す</button>';}
 if(o.type==='image'){if(o.slot)html+='<p class="small-note">写真フレーム：形を保って切り抜いています。下の「トリミング」で中の写真の位置と拡大率を調整できます。</p>';html+='<button id="replaceImage" class="wide">画像を差し替える</button>';html+=options('枠への収め方','fit',o.fit,[['cover','枠いっぱいにトリミング'],['contain','画像全体を表示']]);html+=options('切り抜きの形','mask',o.mask,[['rect','四角'],['ellipse','楕円'],...(F.extraMasks||[])]);html+=range('トリミング拡大','cropZoom',o.cropZoom||1,1,4,.05);html+=range('トリミング X','cropX',o.cropX||0,-1,1,.01)+range('トリミング Y','cropY',o.cropY||0,-1,1,.01);html+=range('明るさ','brightness',o.brightness||100,1,200)+range('コントラスト','contrast',o.contrast||100,1,200)+range('モノクロ','grayscale',o.grayscale||0,0,100);if(F.imageEffects){html+=options('印刷の質感','effect',o.effect||'none',F.imageEffects);html+=`<div class="two-cols">${input('暗い色','ink',o.ink||'#202320','color')}${input('明るい色','paper',o.paper||'#f0daab','color')}</div>`;html+=range('網点サイズ','dotSize',o.dotSize||5,2,16)+range('しきい値 / 加工量','effectAmount',o.effectAmount||128,1,255);}}
 html+=`<div class="advanced-divider"></div><div class="two-cols">${input('X','x',Math.round(o.x),'number','min="-20000" max="20000"')}${input('Y','y',Math.round(o.y),'number','min="-20000" max="20000"')}${input('幅','w',Math.round(o.w),'number','min="1" max="20000"')}${input('高さ','h',Math.round(o.h),'number','min="1" max="20000"')}</div>${range('回転','rotation',o.rotation,0,360)}${range('不透明度','opacity',o.opacity,0,1,.01)}`;
 html+=options('合成モード','blend',o.blend,F.blends);if(!child)html+='<label class="check-label"><input data-prop="mirror" type="checkbox" '+(o.mirror?'checked':'')+'>ミラー</label><p class="small-note">キャンバスの左右中央を軸に、反対側にも表示します。両側を1つのレイヤーとして編集できます。</p>';
 html+='<div class="property-actions"><button id="centerX" title="キャンバス左右中央">左右中央</button><button id="centerY" title="キャンバス上下中央">上下中央</button></div><div class="property-actions"><button id="moveUp">前へ ↑</button><button id="moveDown">後ろへ ↓</button></div><div class="property-actions"><button id="duplicateLayer">複製</button><button id="lockLayer">'+(o.locked?'ロック解除':'ロック')+'</button><button id="deleteLayer" class="delete-button">削除</button></div><button id="exportLayer" class="wide">このレイヤーを透過 PNG に ↓</button>';
 box.innerHTML=html;
 if(o.slot){
 $('selectionType').textContent=child?'枠内の画像':'写真枠';
 const imageKeys=['fit','cropZoom','cropX','cropY','brightness','contrast','grayscale','effect','ink','paper','dotSize','effectAmount'];
 const frameKeys=['x','y','w','h','rotation','opacity','blend','mask'];
 box.querySelectorAll('[data-prop]').forEach(el=>{if((child?frameKeys:imageKeys).includes(el.dataset.prop))(el.closest('.range-control')||el.closest('label'))?.remove();});
 const note=document.createElement('p');note.className='small-note';note.textContent=child?'枠を固定したまま、画像のトリミング・色を調整します。キャンバスをドラッグして画像を移動できます。':'枠の位置・サイズ・形を調整します。中の画像はレイヤー一覧の子行から選べます。';box.prepend(note);
 if(child){for(const id of ['centerX','centerY','moveUp','moveDown','duplicateLayer'])box.querySelector('#'+id)?.remove();const del=box.querySelector('#deleteLayer');if(del)del.textContent='枠内の画像を外す';}
 }
 box.querySelectorAll('[data-prop]').forEach(el=>{el.disabled=o.locked;
 const valueOf=()=>{if(el.type==='number'&&el.value==='')return null;let v=el.type==='checkbox'?el.checked:['number','range'].includes(el.type)||el.dataset.prop==='fontWeight'?Number(el.value):el.value;if(typeof v==='number'){if(!Number.isFinite(v))return null;v=Math.max(el.min?Number(el.min):-Infinity,Math.min(el.max?Number(el.max):Infinity,v));v/=Number(el.dataset.scale||1);}return v;};
 const apply=v=>{o[el.dataset.prop]=v;if(['stickerColor','stickerColorFinish'].includes(el.dataset.prop))o.stickerColorMode='color';if(el.dataset.prop==='text'&&o.role)project.content[o.role]=v;};
 if(el.classList.contains('sticker-text')){el.addEventListener('input',()=>{if(o.locked)return;if(!adjustment){adjustment=snapshot();clearTimeout(saveTimer);}apply(el.value);draw();});el.addEventListener('change',()=>{finishAdjustment();sync();});el.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();cancelAdjustment();}});}
 else if(el.closest('.range-control')){el.addEventListener('input',()=>{if(o.locked)return;const v=valueOf();if(v===null)return;if(!adjustment){adjustment=snapshot();clearTimeout(saveTimer);window.FlyraSelect.close();}apply(v);box.querySelectorAll('[data-prop="'+el.dataset.prop+'"]').forEach(other=>{if(other!==el)other.value=Number((v*Number(other.dataset.scale||1)).toFixed(3));});draw();});
 el.addEventListener('change',()=>{if(o.locked)return;const v=valueOf();if(v!==null&&!adjustment&&v!==o[el.dataset.prop]){adjustment=snapshot();apply(v);}finishAdjustment();sync();});
 el.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();cancelAdjustment();}});el.addEventListener('pointercancel',cancelAdjustment);
 }else el.addEventListener('change',()=>{if(o.locked)return;const v=valueOf();if(v!==null)commit(()=>apply(v));});
 });
 const bind=(id,fn)=>{const b=$(id);if(b){b.disabled=o.locked;b.onclick=fn;}};
 bind('centerX',()=>commit(()=>o.x=(project.width-o.w)/2));bind('centerY',()=>commit(()=>o.y=(project.height-o.h)/2));bind('moveUp',()=>reorder(1));bind('moveDown',()=>reorder(-1));bind('duplicateLayer',duplicate);bind('deleteLayer',remove);bind('reseedLayer',()=>commit(()=>o.seed=seed()));bind('replaceImage',()=>chooseImage(o.id));$('lockLayer').onclick=()=>commit(()=>o.locked=!o.locked);$('exportLayer').onclick=()=>exportImage(true);
}
F.bindLayerDrag($('layerList'),(id,targetId,before)=>{const o=project.layers.find(l=>l.id===id);if(!o||o.locked)return;const ordered=[...project.layers].reverse(),from=ordered.indexOf(o);ordered.splice(from,1);const target=ordered.findIndex(l=>l.id===targetId);if(target<0)return;ordered.splice(target+(before?0:1),0,o);ordered.reverse();if(ordered.every((l,i)=>l===project.layers[i]))return;commit(()=>{project.layers=ordered;selected=id;selectedPart='frame';});toast(o.name+' の重なり順を変更しました');});
function reorder(delta){const o=current();if(!o||o.locked)return;const i=project.layers.indexOf(o),j=i+delta;if(j<0||j>=project.layers.length)return;commit(()=>{project.layers.splice(i,1);project.layers.splice(j,0,o);});}
function duplicate(){const o=current();if(!o||o.locked)return;add({...F.clone(o),id:F.uid(),x:o.x+25,y:o.y+25,name:o.name+' のコピー',role:undefined,userAdded:true});}
function remove(){const o=current();if(!o||o.locked)return;if(o.slot&&o.type==='image'&&selectedPart==='image'){commit(()=>{o.type='rect';o.name=o.frameName||'写真フレーム';delete o.src;o.cropZoom=1;o.cropX=o.cropY=0;selectedPart='frame';});return;}commit(()=>{project.layers=project.layers.filter(x=>x.id!==o.id);selected=null;});}
function add(o){if(project.layers.length>=MAX_LAYERS){toast('レイヤーは150個までです');return;}commit(()=>{project.layers.push(o);selected=o.id;});}
function addShape(type){const w=project.width*.3,h=type==='line'?Math.max(3,project.height*.003):project.height*.24;add(F.layer(type,(project.width-w)/2,(project.height-h)/2,w,h,{color:project.palette[2],color2:project.palette[3],name:({rect:'四角',ellipse:'円',triangle:'三角',star:'星',burst:'バースト',line:'ライン',rings:'リング',grid:'グリッド',checker:'市松',chrome:'クローム',arrow:'矢印'})[type]||type,userAdded:true}));}
function material(){return {type:$('materialType').value,color:$('materialColor').value,color2:$('materialColor2').value,colorFinish:$('materialFinish').value,color2Finish:$('materialFinish2').value,angle:+$('materialAngle').value,density:+$('materialDensity').value,seed:materialSeed};}
function previewMaterial(value){const m=material();if(typeof value==='string')m.type=value;$('angleValue').value=m.angle+'°';$('densityValue').value=m.density;const p={width:360,height:270,background:{type:'solid',color:'#000000',color2:'#ffffff'},layers:[F.layer(m.type,0,0,360,270,{...m})]};F.render($('materialPreview'),p,{transparent:true});}
function downloadBlob(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function safeName(){return project.name.replace(/[\\/:*?"<>|]/g,'_')||'FLYRA';}
function png(canvas){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('画像を生成できませんでした')),'image/png'));}
async function exportImage(layerOnly=false){try{await F.ensureProjectFonts(layerOnly?{layers:current()?[current()]:[]}:project);const scale=layerOnly?1:+$('exportScale').value;let p=project,only=current();if(layerOnly&&!only)return;let w=Math.round(p.width*scale),h=Math.round(p.height*scale);if(w*h>40000000){toast('出力が大きすぎます。標準（1倍）を選んでください。');return;}const c=document.createElement('canvas');c.width=w;c.height=h;const format=layerOnly?'png':$('exportFormat').value;F.render(c,p,{images,transparent:layerOnly||format==='png'&&$('transparentExport').checked,onlyLayer:layerOnly?only:null});const blob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('画像を保存できませんでした')),format==='jpeg'?'image/jpeg':'image/png',.95));downloadBlob(blob,safeName()+(layerOnly?'-layer':'')+'.'+(format==='jpeg'?'jpg':'png'));toast(`${w} × ${h} px で書き出しました`);if(!layerOnly)$('exportDialog').close();}catch(e){toast(e.message);}}
function exportDimensions(){const s=+$('exportScale').value;$('exportDimensions').textContent=`${Math.round(project.width*s)} × ${Math.round(project.height*s)} px`;$('transparentExport').disabled=$('exportFormat').value!=='png';}
let replaceId=null;
function chooseImage(id=null){replaceId=id;$('imageInput').click();}
async function importImage(file,id=null){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>20*1024*1024){toast('20MB 以下の PNG / JPEG / WebP を選んでください');return;}try{const assetName=await F.resolveAssetName(file,allAssets());const url=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('ファイルを読み込めません'));reader.readAsDataURL(file);});const sticker=await F.stickerForSource(url);const image=await F.loadImage(url);const c=document.createElement('canvas'),ratio=Math.min(1,2400/Math.max(image.width,image.height));c.width=Math.max(1,Math.round(image.width*ratio));c.height=Math.max(1,Math.round(image.height*ratio));c.getContext('2d').drawImage(image,0,0,c.width,c.height);const src=c.toDataURL('image/png');if(src.length>15000000){toast('画像が大きすぎます。解像度を下げてください。');return;}images.set(src,await F.loadImage(src));const target=project.layers.find(o=>o.id===id);if(id&&(!target||target.locked)){toast('写真枠を選択し直すか、ロックを解除してください');return;}if(target&&!target.locked){commit(()=>{if(target.slot&&!target.frameName)target.frameName=target.type==='image'?'写真フレーム':target.name;for(const [key] of F.stickerFields)delete target[key];delete target.stickerKind;Object.assign(target,sticker);target.type='image';target.src=src;target.fit='cover';target.cropZoom=1;target.cropX=0;target.cropY=0;target.mask=target.mask||'rect';target.name=assetName;target.userAdded=true;project.layers=project.layers.filter(o=>o.placeholderFor!==target.id);selected=target.id;selectedPart=target.slot?'image':'frame';});}else{const w=project.width*.66,h=Math.min(project.height*.65,w*image.height/image.width);add(F.layer('image',(project.width-w)/2,(project.height-h)/2,w,h,{name:assetName,...sticker,src,fit:'contain',mask:'rect',brightness:100,contrast:100,grayscale:0,userAdded:true}));}toast('画像を追加しました');}catch(e){toast('画像を読み込めませんでした。別の画像でお試しください。');}}
function point(e){const r=art.getBoundingClientRect();return {x:(e.clientX-r.left)*project.width/r.width,y:(e.clientY-r.top)*project.height/r.height};}
function handleAtOne(o,p){if(!o||o.locked||!o.visible||(o.slot&&selectedPart==='image'))return null;const u=project.width/art.getBoundingClientRect().width,q=F.localPoint(o,p.x,p.y),h=F.rotationHandle(o,u,project.width,project.height);if(Math.hypot(q.x-h.x,q.y-h.y)<11*u)return{mode:'rotate'};for(const sx of [-1,1])for(const sy of [-1,1])if(Math.hypot(q.x-(sx<0?0:o.w),q.y-(sy<0?0:o.h))<11*u)return{mode:'resize',sx,sy};return null;}
function handleAt(o,p){const direct=handleAtOne(o,p);if(direct)return direct;if(o?.mirror){const reflected=handleAtOne(o,{x:project.width-p.x,y:p.y});if(reflected)return {...reflected,mirrorSide:true};}return null;}
art.addEventListener('pointerdown',e=>{if(e.button!==0)return;finishAdjustment();art.focus();const p=point(e),o=current(),handle=handleAt(o,p);const cropping=o?.slot&&!o.locked&&o.visible&&o.type==='image'&&selectedPart==='image'&&F.hit(o,p.x,p.y,project.width);let target=cropping?o:handle?o:[...project.layers].reverse().find(l=>l.visible&&!l.locked&&F.hit(l,p.x,p.y,project.width));select(target?.id||null,cropping?'image':'frame');if(!target)return;e.preventDefault();clearTimeout(saveTimer);const mirrorSide=handle?.mirrorSide||F.isMirrorHit(target,p.x,p.y,project.width);drag={mirrorSide,start:mirrorSide?{x:project.width-p.x,y:p.y}:p,original:F.clone(target),mode:cropping?'crop':'move',...handle,moved:false,before:snapshot()};art.setPointerCapture(e.pointerId);});
art.addEventListener('pointermove',e=>{
 const p=point(e);if(!drag){const h=handleAt(current(),p);art.style.cursor=h?.mode==='rotate'?'grab':h?.mode==='resize'?(h.sx===h.sy?'nwse-resize':'nesw-resize'):'default';return;}
 if(drag.mirrorSide)p.x=project.width-p.x;const o=current();if(!o)return;const dx=p.x-drag.start.x,dy=p.y-drag.start.y,old=drag.original,u=project.width/art.getBoundingClientRect().width;drag.moved=drag.moved||Math.hypot(dx,dy)>u;drag.snapX=drag.snapY=false;
 if(drag.mode==='crop'){const im=images.get(o.src);if(im){const a=old.rotation*Math.PI/180,rx=dx*Math.cos(a)+dy*Math.sin(a),ry=-dx*Math.sin(a)+dy*Math.cos(a),ratio=(old.fit==='contain'?Math.min:Math.max)(old.w/im.width,old.h/im.height)*(old.cropZoom||1),mx=Math.abs(old.w-im.width*ratio)/2,my=Math.abs(old.h-im.height*ratio)/2;o.cropX=mx?Math.max(-1,Math.min(1,(old.cropX||0)+rx/mx)):0;o.cropY=my?Math.max(-1,Math.min(1,(old.cropY||0)+ry/my)):0;}}
 else if(drag.mode==='move'){o.x=old.x+dx;o.y=old.y+dy;if(!e.altKey){if(Math.abs(o.x+o.w/2-project.width/2)<8*u){o.x=(project.width-o.w)/2;drag.snapX=true;}if(Math.abs(o.y+o.h/2-project.height/2)<8*u){o.y=(project.height-o.h)/2;drag.snapY=true;}}}
 else if(drag.mode==='rotate'){const cx=old.x+old.w/2,cy=old.y+old.h/2;let angle=F.normalizeRotation(old.rotation+(Math.atan2(p.y-cy,p.x-cx)-Math.atan2(drag.start.y-cy,drag.start.x-cx))*180/Math.PI);if(e.shiftKey)angle=F.normalizeRotation(Math.round(angle/15)*15);else if(!e.altKey&&Math.abs(angle-Math.round(angle/90)*90)<3)angle=F.normalizeRotation(Math.round(angle/90)*90);o.rotation=angle;}
 else Object.assign(o,F.resizeCorner(old,dx,dy,drag.sx,drag.sy,e.shiftKey||(o.type==='image'&&!o.slot)));
 $('properties').querySelectorAll('[data-prop]').forEach(el=>{if(['x','y','w','h','rotation','fontSize','cropX','cropY'].includes(el.dataset.prop)){const value=o[el.dataset.prop]??0;el.value=Number(Number(value).toFixed(2));}});draw();
});
function endDrag(){if(!drag)return;if(!sameState(project,drag.before)){undoStack.push(drag.before);trimHistory();redoStack=[];}drag=null;scheduleSave();sync();}
function cancelDrag(){if(!drag)return;project=drag.before;drag=null;scheduleSave();sync();}
art.addEventListener('pointerup',endDrag);art.addEventListener('pointercancel',cancelDrag);
art.addEventListener('keydown',e=>{if(e.key==='Escape'&&drag){e.preventDefault();e.stopPropagation();cancelDrag();}});
function photoFrameAt(e){const p=point(e);return [...project.layers].reverse().find(o=>o.slot&&o.visible&&!o.locked&&F.hit(o,p.x,p.y,project.width));}
art.addEventListener('dblclick',e=>{const frame=photoFrameAt(e);if(frame){select(frame.id);chooseImage(frame.id);}else if(current()?.type==='text')$('properties').querySelector('textarea')?.focus();});
document.addEventListener('keydown',e=>{if(document.activeElement.closest('.preview-menu,.preview-select,.context-menu')||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)||document.querySelector('dialog[open]'))return;const cmd=e.ctrlKey||e.metaKey;if(cmd&&e.key.toLowerCase()==='z'){e.preventDefault();history(e.shiftKey?'redo':'undo');}else if(cmd&&e.key.toLowerCase()==='y'){e.preventDefault();history('redo');}else if(cmd&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate();}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove();}else if(e.key==='Escape')select(null);else if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){const o=current();if(!o||o.locked)return;e.preventDefault();const n=e.shiftKey?10:1;if(o.slot&&o.type==='image'&&selectedPart==='image'){commit(()=>{o.cropX=Math.max(-1,Math.min(1,(o.cropX||0)+(e.key==='ArrowLeft'?-n:e.key==='ArrowRight'?n:0)/100));o.cropY=Math.max(-1,Math.min(1,(o.cropY||0)+(e.key==='ArrowUp'?-n:e.key==='ArrowDown'?n:0)/100));});return;}commit(()=>{o.x+=e.key==='ArrowLeft'?-n:e.key==='ArrowRight'?n:0;o.y+=e.key==='ArrowUp'?-n:e.key==='ArrowDown'?n:0;});}});
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id==='panel-'+b.dataset.panel));if(window.innerWidth<600)$('panel-'+b.dataset.panel).scrollIntoView({behavior:'smooth',block:'start'});});
function renderFilters(){const row=document.querySelector('.filter-row');row.replaceChildren();for(const c of [{id:'all',name:'すべて'},...F.siteConfig.categories]){const b=document.createElement('button');b.dataset.filter=c.id;b.className='chip'+(filter===c.id?' active':'');b.textContent=c.name;b.onclick=()=>{filter=c.id;renderFilters();renderTemplates();};row.append(b);}}
document.querySelectorAll('[data-shape]').forEach(b=>b.onclick=()=>addShape(b.dataset.shape));
$('addText').onclick=()=>{const w=project.width*.7,h=project.height*.14;add(F.layer('text',project.width*.15,project.height*.43,w,h,{name:'追加テキスト',text:'ここにテキスト',font:'sans',fontWeight:700,fontSize:project.width*.08,lineHeight:1.1,align:'left',color:project.palette[1],userAdded:true}));};
for(const key of Object.keys(F.defaultContent))$('content-'+key).addEventListener('change',e=>{commit(()=>{project.content[key]=e.target.value;project.layers.filter(o=>o.role===key&&!o.locked).forEach(o=>o.text=e.target.value);});if(project.layers.some(o=>o.role===key&&o.locked))toast('ロック中の文字は変更していません');});
$('projectName').onchange=e=>commit(()=>project.name=e.target.value.trim()||'名称未設定');
$('undo').onclick=()=>history('undo');$('redo').onclick=()=>history('redo');
$('sizePreset').onchange=e=>commit(()=>{const [w,h]=e.target.value.split(',').map(Number);F.resizeProject(project,w,h);zoom=1;});
function setZoom(value,x,y){const area=$('canvasArea'),before=art.getBoundingClientRect(),next=Math.max(.4,Math.min(3,value));if(next===zoom)return;const viewport=area.getBoundingClientRect();x??=viewport.left+viewport.width/2;y??=viewport.top+viewport.height/2;const fx=(x-before.left)/before.width,fy=(y-before.top)/before.height;zoom=next;fit();const after=art.getBoundingClientRect();area.scrollLeft+=after.left+fx*after.width-x;area.scrollTop+=after.top+fy*after.height-y;$('zoomFit').title='フィットに戻す · '+Math.round(zoom*100)+'%';}
let wheelFrame=0,wheelZoom=null,wheelPoint=null;
$('canvasArea').addEventListener('wheel',e=>{e.preventDefault();if(drag||previewProject||!e.deltaY)return;const unit=e.deltaMode===1?16:e.deltaMode===2?$('canvasArea').clientHeight:1,delta=Math.max(-120,Math.min(120,e.deltaY*unit));wheelZoom=Math.max(.4,Math.min(3,(wheelZoom??zoom)*Math.exp(-delta*.0015)));wheelPoint={x:e.clientX,y:e.clientY};if(!wheelFrame)wheelFrame=requestAnimationFrame(()=>{wheelFrame=0;const next=wheelZoom,p=wheelPoint;wheelZoom=null;setZoom(next,p.x,p.y);});},{passive:false});
function clearWheel(){cancelAnimationFrame(wheelFrame);wheelFrame=0;wheelZoom=null;}
$('toggleGuides').onclick=()=>{guides=!guides;$('toggleGuides').setAttribute('aria-pressed',guides);drawOverlay();};$('zoomIn').onclick=()=>{clearWheel();setZoom(zoom+.2);};$('zoomOut').onclick=()=>{clearWheel();setZoom(zoom-.2);};$('zoomFit').onclick=()=>{clearWheel();zoom=1;fit();$('canvasArea').scrollTop=0;$('canvasArea').scrollLeft=0;$('zoomFit').title='全体を表示';};
$('shufflePalette').onclick=()=>commit(()=>{const candidates=F.palettes.filter(p=>JSON.stringify(p)!==JSON.stringify(project.palette));F.recolor(project,candidates[Math.floor(Math.random()*candidates.length)]);});
$('randomize').onclick=()=>{const candidates=F.templates.filter(t=>t.id!==project.template&&(filter==='all'||t.category===filter));if(!candidates.length){toast('この分類には他のテンプレートがありません');return;}commit(()=>{project=F.applyTemplate(project,candidates[Math.floor(Math.random()*candidates.length)].id,seed());selected=null;});toast('新しい案です。↶ で前の案に戻れます');};
$('shuffleLayout').onclick=()=>commit(()=>{const old=project.palette.slice(),candidates=F.templates.filter(t=>t.id!==project.template&&(filter==='all'||t.category===filter));if(!candidates.length)throw Error('この分類には他のテンプレートがありません');project=F.applyTemplate(project,candidates[Math.floor(Math.random()*candidates.length)].id,seed());F.recolor(project,old);selected=null;});
for(const id of ['materialType','materialColor','materialColor2','materialFinish','materialFinish2','materialAngle','materialDensity'])$(id).addEventListener('input',previewMaterial);
$('materialReseed').onclick=()=>{materialSeed=seed();previewMaterial();};$('addMaterial').onclick=()=>{const m=material();add(F.layer(m.type,project.width*.12,project.height*.18,project.width*.76,project.height*.64,{...m,name:$('materialType').selectedOptions[0].text,userAdded:true}));};
$('setBackground').onclick=()=>commit(()=>project.background=material());
$('materialDownload').onclick=async()=>{try{const m=material(),c=document.createElement('canvas');c.width=1600;c.height=1200;F.render(c,{width:1600,height:1200,layers:[F.layer(m.type,0,0,1600,1200,{...m})]},{transparent:true});downloadBlob(await png(c),'FLYRA-'+m.type+'.png');toast('1600 × 1200 px の素材を保存しました');}catch(e){toast(e.message);}};
$('uploadImage').onclick=()=>chooseImage(current()?.slot&&!current().locked?current().id:null);$('imageInput').onchange=e=>{const id=replaceId;replaceId=null;importImage(e.target.files[0],id);e.target.value='';};
$('canvasArea').addEventListener('dragover',e=>e.preventDefault());$('canvasArea').addEventListener('drop',async e=>{e.preventDefault();const files=[...e.dataTransfer.files].slice(0,10),frame=photoFrameAt(e);for(let i=0;i<files.length;i++)await importImage(files[i],i===0?frame?.id:null);});
$('saveProject').onclick=()=>{downloadBlob(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),safeName()+'.flyra');toast('編集データを保存しました');};$('openProject').onclick=()=>$('projectInput').click();$('projectInput').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>50*1024*1024){toast('編集データは50MB 以下にしてください');return;}try{const next=F.validate(JSON.parse(await file.text()));await F.restoreStickers(next);const loaded=await F.prepare(next);commit(()=>{project=next;images=loaded;selected=null;zoom=1;});toast('編集データを開きました');}catch(err){toast(err.message||'読み込みに失敗しました');}};
$('export').onclick=()=>{exportDimensions();$('exportDialog').showModal();};$('exportScale').onchange=exportDimensions;$('exportFormat').onchange=exportDimensions;$('downloadExport').onclick=()=>exportImage();$('help').onclick=()=>$('helpDialog').showModal();
function allAssets(){return [...(window.FLYRA_ASSETS||[]),...customAssets];}
function renderAssets(previewFolder){const folder=typeof previewFolder==='string'?previewFolder:$('assetFolder').value,list=$('assetGrid');list.replaceChildren();const assets=allAssets().filter(a=>folder==='mine'?a.custom:a.folder===folder);for(const a of assets){const card=document.createElement('button');card.dataset.assetId=a.id;card.className='asset-card'+(assetSelection.has(a.id)?' selected':'');card.setAttribute('aria-label',a.name+' 素材を選択');card.setAttribute('aria-pressed',String(assetSelection.has(a.id)));const image=document.createElement('img');image.src=a.src;image.alt='';image.loading='lazy';const name=document.createElement('span');name.textContent=a.name;const tag=document.createElement('small');tag.textContent=a.custom?'MY ASSET':'LIBRARY';card.append(image,name,tag);card.onclick=()=>{assetSelection.has(a.id)?assetSelection.delete(a.id):assetSelection.add(a.id);renderAssets();};list.appendChild(card);}if(!assets.length){const p=document.createElement('p');p.className='small-note';p.textContent='画像やフォルダを登録すると、ここに並びます。';list.appendChild(p);}const count=assetSelection.size;$('addSelectedAssets').disabled=!count;$('addSelectedAssets').textContent=count?`選択した ${count} 点を追加 ＋`:'選択した素材を追加';}
async function storeAssets(){if(!db){toast('素材棚の自動保存が使えません。「素材棚を保存」で残してください');return;}await new Promise((resolve,reject)=>{const tx=db.transaction('assets','readwrite');tx.objectStore('assets').put(customAssets,'library');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
async function readAsset(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>20*1024*1024)throw new Error(file.name+'：対応形式・サイズ外');const src=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const im=await F.loadImage(src),c=document.createElement('canvas'),ratio=Math.min(1,2400/Math.max(im.width,im.height));c.width=Math.round(im.width*ratio);c.height=Math.round(im.height*ratio);c.getContext('2d').drawImage(im,0,0,c.width,c.height);const result=c.toDataURL('image/png');if(result.length>15000000)throw new Error('解像度が大きすぎます');return result;}
async function registerAssets(files){const accepted=[...files].filter(f=>['image/png','image/jpeg','image/webp'].includes(f.type));if(customAssets.length+accepted.length>100){toast('素材棚への登録は100点までです');return;}const folder=$('assetFolder').value==='mine'?'icons':$('assetFolder').value;let count=0;for(const file of accepted){try{const name=await F.resolveAssetName(file,allAssets());const src=await readAsset(file),sticker=await F.stickerForSource(src);customAssets.push({id:F.uid(),name:name.slice(0,160),...sticker,folder,src,custom:true,blend:folder==='textures'?'overlay':'source-over',opacity:1});count++;}catch(e){toast(e.message||'画像を登録できませんでした');}}try{await storeAssets();}catch{toast('自動保存できませんでした。「素材棚を保存」を使ってください');}renderAssets();toast(count?`${count} 点を素材棚に登録しました`:'PNG / JPEG / WebP が見つかりませんでした');}
$('assetFolder').onchange=()=>{assetSelection.clear();renderAssets();};$('importAssets').onclick=()=>$('assetsInput').click();$('importAssetFolder').onclick=()=>$('assetFolderInput').click();for(const id of ['assetsInput','assetFolderInput'])$(id).onchange=async e=>{await registerAssets(e.target.files);e.target.value='';};
$('addSelectedAssets').onclick=async()=>{const assets=allAssets().filter(a=>assetSelection.has(a.id));if(project.layers.length+assets.length>MAX_LAYERS){toast('レイヤーは150個までです');return;}try{const layers=[];for(const a of assets){const src=await F.assetDataURL(a);const im=await F.loadImage(src);images.set(src,im);const texture=a.folder==='textures',w=texture?project.width:project.width*.35,h=texture?project.height:w*im.height/im.width;layers.push(F.layer('image',texture?0:(project.width-w)/2+layers.length*18,texture?0:(project.height-h)/2+layers.length*18,w,h,{name:a.name,...(F.stickerDefaults[a.stickerKind]?{stickerKind:a.stickerKind,...F.stickerDefaults[a.stickerKind]}:{}),src:a.src,fit:texture?'cover':'contain',mask:'rect',brightness:100,contrast:100,grayscale:0,blend:a.blend||'source-over',opacity:a.opacity??1,userAdded:true}));}commit(()=>{project.layers.push(...layers);selected=layers.at(-1)?.id;});assetSelection.clear();renderAssets();toast(`${layers.length} 点の素材を追加しました`);}catch(e){toast('素材の読み込みに失敗しました');}};
$('saveAssetLibrary').onclick=()=>{downloadBlob(new Blob([JSON.stringify({format:'flyra-assets',version:1,assets:customAssets})],{type:'application/json'}),'FLYRA-my-assets.json');toast('自分で登録した素材を保存しました');};$('loadAssetLibrary').onclick=()=>$('assetLibraryInput').click();$('assetLibraryInput').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>150*1024*1024){toast('素材棚ファイルは150MBまでです');return;}try{const data=JSON.parse(await file.text());if(data.format!=='flyra-assets'||data.version!==1||!Array.isArray(data.assets)||data.assets.length>100)throw Error();const incoming=[];for(const a of data.assets){if(!a||typeof a.name!=='string'||a.name.length>160||!['textures','icons','logos','barcodes'].includes(a.folder)||typeof a.src!=='string'||a.src.length>15000000||!/^data:image\/(png|jpeg|webp);base64,[a-z0-9+/=]+$/i.test(a.src))throw Error();await F.loadImage(a.src);incoming.push({id:F.uid(),name:a.name,...await F.stickerForSource(a.src),folder:a.folder,src:a.src,custom:true,blend:a.folder==='textures'?'overlay':'source-over',opacity:1});}if(customAssets.length+incoming.length>100){toast('登録済み素材と合わせて100点を超えます');return;}customAssets.push(...incoming);await storeAssets();$('assetFolder').value='mine';renderAssets();toast(`${incoming.length} 点を素材棚に読み込みました`);}catch{toast('素材棚ファイルを読み込めませんでした');}};

// Preview a separate render snapshot. Saved project and undo history never change.
document.addEventListener('optionpreview',e=>{
 const el=e.target,value=e.detail.value;
 if(el.dataset.prop==='bgFinish'){previewProject={...project,background:{...project.background,colorFinish:value}};draw();}
 else if(el.id==='materialFinish'||el.id==='materialFinish2'){const m=material();m[el.id==='materialFinish'?'colorFinish':'color2Finish']=value;F.render($('materialPreview'),{width:360,height:270,background:{type:'solid',color:'#000000',color2:'#ffffff'},layers:[F.layer(m.type,0,0,360,270,m)]},{transparent:true});}
 else if(el.dataset.prop){const o=current();if(!o||o.locked)return;previewProject={...project,layers:project.layers.map(x=>x.id===o.id?{...x,...(el.dataset.prop==='stickerColorFinish'?{stickerColorMode:'color'}:{}),[el.dataset.prop]:el.dataset.prop==='fontWeight'?Number(value):value,...(el.dataset.prop==='font'?{fontWeight:o.fontWeight}:{})}:x)};draw();const snapshot=previewProject;F.ensureProjectFonts(snapshot).then(()=>{if(previewProject===snapshot)draw();}).catch(()=>{if(previewProject===snapshot)toast('この書体はネット接続が必要です');});}
 else if(el.id==='materialType')previewMaterial(value);
 else if(el.id==='assetFolder')renderAssets(value);
 else if(el.id==='sizePreset'){previewProject=snapshot();const [w,h]=value.split(',').map(Number);F.resizeProject(previewProject,w,h);$('canvasInfo').textContent=w+' × '+h+' px · プレビュー';const area=$('canvasArea'),scale=Math.min((area.clientWidth-68)/w,(area.clientHeight-68)/h)*zoom;const dpr=Math.min(window.devicePixelRatio||1,2);$('canvasWrap').style.width=Math.max(40,w*scale)+'px';$('canvasWrap').style.height=Math.max(40,h*scale)+'px';renderWidth=Math.round(Math.max(40,w*scale)*dpr);renderHeight=Math.round(Math.max(40,h*scale)*dpr);draw();}
 else if(el.id==='exportScale')$('exportDimensions').textContent=Math.round(project.width*Number(value))+' × '+Math.round(project.height*Number(value))+' px · プレビュー';
 else if(el.id==='exportFormat')$('exportDimensions').textContent=(value==='jpeg'?'JPEG · 背景付き':'PNG · 透過に対応')+' · プレビュー';
});
document.addEventListener('previewcancel',e=>{previewProject=null;if(['materialType','materialFinish','materialFinish2'].includes(e.target.id))previewMaterial();else if(e.target.id==='assetFolder')renderAssets();else if(e.target.id==='sizePreset'){$('canvasInfo').textContent=project.width+' × '+project.height+' px';fit();}else if(e.target.id.startsWith('export'))exportDimensions();draw();});
new ResizeObserver(fit).observe($('canvasArea'));

// Context actions reuse the same selection, commit and undo paths as the editor.
let layerClipboard=null;
const menuItem=(label,run,disabled=false,extra={})=>({label,run,disabled,...extra});
function copyLayer(){const o=current();if(o){layerClipboard=F.clone(o);toast('レイヤーをコピーしました');}}
async function pasteLayer(){if(!layerClipboard)return;const o={...F.clone(layerClipboard),id:F.uid(),name:layerClipboard.name+' のコピー',x:layerClipboard.x+25,y:layerClipboard.y+25,role:undefined,userAdded:true,locked:false};if(o.src)images.set(o.src,await F.loadImage(o.src));selectedPart='frame';add(o);}
function layerMenu(o){
 const blocked=o.locked,idx=project.layers.indexOf(o);
 const moveTo=front=>commit(()=>{project.layers=project.layers.filter(x=>x.id!==o.id);front?project.layers.push(o):project.layers.unshift(o);});
 const items=[menuItem('お気に入り登録',registerFavorite),null,menuItem('コピー',copyLayer),menuItem('切り取り',()=>{copyLayer();commit(()=>{project.layers=project.layers.filter(x=>x.id!==o.id);selected=null;});},blocked),menuItem('複製',duplicate,blocked),menuItem('貼り付け',pasteLayer,!layerClipboard),null,
 menuItem('最前面へ',()=>moveTo(true),blocked||idx===project.layers.length-1),menuItem('1つ前へ',()=>reorder(1),blocked||idx===project.layers.length-1),menuItem('1つ後ろへ',()=>reorder(-1),blocked||idx===0),menuItem('最背面へ',()=>moveTo(false),blocked||idx===0),null,
 menuItem('左右中央に揃える',()=>commit(()=>o.x=(project.width-o.w)/2),blocked),menuItem('上下中央に揃える',()=>commit(()=>o.y=(project.height-o.h)/2),blocked),menuItem('ミラー',()=>commit(()=>o.mirror=!o.mirror),blocked,{checked:!!o.mirror})];
 if(o.type==='text'){items.push(null);for(const [value,label] of [['normal','通常'],['arc','アーチ'],['vertical','縦書き']])items.push(menuItem(label,()=>commit(()=>o.textShape=value),blocked,{checked:(o.textShape||'normal')===value}));}
 if(o.type==='image'||o.slot)items.push(menuItem(o.slot?'枠の画像を差し替える':'画像を差し替える',()=>chooseImage(o.id),blocked));
 items.push(null,menuItem(o.locked?'ロック解除':'ロック',()=>commit(()=>o.locked=!o.locked)),menuItem(o.visible?'非表示にする':'表示する',()=>commit(()=>o.visible=!o.visible)),menuItem('このレイヤーをPNGで保存',()=>exportImage(true)),menuItem('削除',()=>commit(()=>{project.layers=project.layers.filter(x=>x.id!==o.id);selected=null;}),blocked,{danger:true}));return items;
}
function canvasMenu(){return [menuItem('元に戻す',()=>history('undo'),!undoStack.length),menuItem('やり直す',()=>history('redo'),!redoStack.length),null,menuItem('貼り付け',pasteLayer,!layerClipboard),menuItem('テキストを追加',()=>$('addText').click()),menuItem('画像を追加',()=>chooseImage()),null,menuItem('全体を表示',()=>$('zoomFit').click()),menuItem('余白ガイド',()=>$('toggleGuides').click(),false,{checked:guides}),menuItem('書き出す',()=>$('export').click())];}
document.addEventListener('contextmenu',e=>{
 if(e.target.closest('input,textarea,select,[contenteditable="true"]'))return;
 let items,title;
 const favorite=e.target.closest('.favorite-card');
 const row=e.target.closest('[data-layer-id]'),child=e.target.closest('[data-frame-child]'),asset=e.target.closest('.asset-card'),template=e.target.closest('.template-card');
 if(favorite){const f=project.favorites?.find(f=>f.id===favorite.dataset.favoriteId);if(!f)return;title=f.name;items=[menuItem('キャンバスに追加',()=>addFavorite(f.id)),menuItem('お気に入りから削除',()=>removeFavorite(f.id),false,{danger:true})];}
 else if(row||child){const o=project.layers.find(o=>o.id===(row?.dataset.layerId||child.dataset.frameChild));if(!o)return;select(o.id);items=layerMenu(o);title=o.name;}
 else if(asset){const a=allAssets().find(a=>a.id===asset.dataset.assetId);if(!a)return;title=a.name;items=[menuItem('キャンバスに追加',async()=>{assetSelection=new Set([a.id]);await $('addSelectedAssets').onclick();}),menuItem(assetSelection.has(a.id)?'選択を解除':'まとめて追加する素材に選択',()=>{assetSelection.has(a.id)?assetSelection.delete(a.id):assetSelection.add(a.id);renderAssets();}),menuItem('素材名をコピー',()=>navigator.clipboard.writeText(a.name))];}
 else if(template){const t=F.templates.find(t=>t.id===template.dataset.template);if(!t)return;title=t.name;items=[menuItem('このテンプレートを適用',()=>template.click()),menuItem('告知内容を編集',()=>document.querySelector('[data-panel="content"]').click())];}
 else if(e.target.closest('#canvasArea')){finishAdjustment();const p=point(e),o=[...project.layers].reverse().find(o=>F.hit(o,p.x,p.y,project.width));select(o?.id||null);title=o?o.name:'キャンバス';items=o?layerMenu(o):canvasMenu();}
 else if(e.target.closest('#properties')){const o=current();title=o?o.name:'キャンバス';items=o?layerMenu(o):canvasMenu();}
 else if(e.target.closest('#layerList')){title='レイヤー';items=canvasMenu();}
 else return;
 window.FlyraSelect.close();F.openContextMenu(e,title,items);
});


let favoriteRevision=0;
function registerFavorite(){const o=current();if(!o)return;if((project.favorites||[]).length>=100){toast('お気に入りは100件までです');return;}commit(()=>{project.favorites||=[];project.favorites.push(F.favoriteFromLayer(project,o));});toast('お気に入りに登録しました');}
async function addFavorite(id){const f=project.favorites?.find(f=>f.id===id);if(!f)return;try{const o=F.layerFromFavorite(project,f);if(o.src)images.set(o.src,await F.loadImage(o.src));selectedPart='frame';add(o);}catch{toast('お気に入りを読み込めませんでした');}}
function removeFavorite(id){commit(()=>{project.favorites=(project.favorites||[]).filter(f=>f.id!==id);});}
function renderFavorites(){
 const revision=++favoriteRevision,list=$('favoriteGrid');list.replaceChildren();
 if(!project.favorites?.length){const note=document.createElement('p');note.className='small-note';note.textContent='レイヤーを右クリックして「お気に入り登録」。文字・図形・画像の見た目と設定を、このプロジェクトに保存できます。';list.append(note);return;}
 for(const f of project.favorites){const card=document.createElement('button');card.type='button';card.className='favorite-card';card.dataset.favoriteId=f.id;card.setAttribute('aria-label',f.name+' お気に入りを追加');const canvas=document.createElement('canvas');canvas.width=220;canvas.height=Math.max(90,Math.round(220*f.height/f.width));const name=document.createElement('span');name.textContent=f.name;card.append(canvas,name);card.onclick=()=>addFavorite(f.id);list.append(card);
 const p={...project,width:f.width,height:f.height,layers:[{...f.layer,visible:true}]};Promise.all([F.prepare(p),F.ensureProjectFonts(p)]).then(([loaded])=>{if(revision===favoriteRevision)F.render(canvas,p,{images:loaded,transparent:true});}).catch(()=>{name.textContent=f.name+'（プレビューを読み込めません）';});
 }
}

async function init(){await Promise.all([initStorage(),F.loadSiteLibrary()]);const restored=await F.restoreStickers(project);for(const a of customAssets){if(!a.stickerKind)Object.assign(a,await F.stickerForSource(a.src));}renderFilters();renderTemplates();renderAssets();previewMaterial();sync();if(restored)scheduleSave();}
init().catch(e=>{toast('起動に失敗しました。ページを再読み込みしてください。');console.error(e);});
})();
