/* FLYRA UI — everything stays on this device. */
(() => {
'use strict';
const F=window.Flyra,$=id=>document.getElementById(id),art=$('artboard'),overlay=$('overlay');
let project=F.makeProject(),selected=null,images=new Map(),undoStack=[],redoStack=[],zoom=1,guides=false,drag=null,saveTimer,toastTimer,renderQueued=false,filter='all',materialSeed=501,db=null,saving=Promise.resolve(),customAssets=[],assetSelection=new Set();
const MAX_LAYERS=150,historyLimit=40;
const seed=()=>Math.floor(Math.random()*2147483647);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3400);}
let previewProject=null;
let fontLoadRevision=0;
function loadProjectFonts(){const rev=++fontLoadRevision;F.ensureProjectFonts(project).then(()=>{if(rev===fontLoadRevision){draw();const status=$('fontStatus');if(status)status.textContent='書体を読み込み済み · 太さは書体ごとの対応範囲';}}).catch(()=>{if(rev===fontLoadRevision){const status=$('fontStatus');if(status)status.textContent='書体を読み込めません。ネット接続を確認して再読み込みしてください。';toast('オンライン書体を読み込めません。標準書体で一時表示しています。');}});}
function current(){return project.layers.find(o=>o.id===selected);}
function trimHistory(){const weight=project.layers.reduce((n,o)=>n+(o.src?.length||0)*2+1000,1000),limit=Math.max(2,Math.min(historyLimit,Math.floor(64000000/weight)));while(undoStack.length>limit)undoStack.shift();}
function pushHistory(){undoStack.push(F.clone(project));trimHistory();redoStack=[];}
function commit(action,{refresh=true}={}){const priorRedo=redoStack;pushHistory();try{action();}catch(e){project=undoStack.pop();redoStack=priorRedo;sync();toast(e.message||'変更できませんでした');return;}scheduleSave();if(refresh)sync();else{draw();updateUndo();}}
function scheduleSave(){clearTimeout(saveTimer);$('saveStatus').textContent='保存中…';saveTimer=setTimeout(()=>{const snapshot=F.clone(project);saving=saving.then(()=>persist(snapshot)).catch(()=>{$('saveStatus').textContent='自動保存できません · データ保存を利用';});},400);}
function persist(p){return new Promise((resolve,reject)=>{if(!db){try{localStorage.setItem('flyra-project-v1',JSON.stringify(p));$('saveStatus').textContent='この端末に保存済み';resolve();}catch(e){reject(e);}return;}const tx=db.transaction('projects','readwrite');tx.objectStore('projects').put(p,'current');tx.oncomplete=()=>{$('saveStatus').textContent='この端末に保存済み';resolve();};tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
async function initStorage(){try{db=await new Promise((resolve,reject)=>{const req=indexedDB.open('flyra-studio',2);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('projects'))req.result.createObjectStore('projects');if(!req.result.objectStoreNames.contains('assets'))req.result.createObjectStore('assets');};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});const stored=await new Promise((resolve,reject)=>{const req=db.transaction('projects').objectStore('projects').get('current');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});if(stored){project=F.validate(stored);images=await F.prepare(project);toast('前回のデザインを復元しました');}customAssets=await new Promise((resolve,reject)=>{const req=db.transaction('assets').objectStore('assets').get('library');req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error);});}catch(e){try{const stored=localStorage.getItem('flyra-project-v1');if(stored){project=F.validate(JSON.parse(stored));images=await F.prepare(project);}}catch(e2){toast('保存データを復元できませんでした。保存ファイルから開いてください。');}if(!db)$('saveStatus').textContent='このブラウザの保存機能は制限されています';}}
function updateUndo(){$('undo').disabled=!undoStack.length;$('redo').disabled=!redoStack.length;}
async function history(direction){const from=direction==='undo'?undoStack:redoStack,to=direction==='undo'?redoStack:undoStack;if(!from.length)return;to.push(F.clone(project));project=from.pop();selected=null;images=await F.prepare(project);sync();scheduleSave();}
function fit(){const area=$('canvasArea'),pad=window.innerWidth<600?40:68;const scale=Math.min((area.clientWidth-pad)/project.width,(area.clientHeight-pad)/project.height)*zoom;const width=Math.max(40,project.width*scale),height=Math.max(40,project.height*scale);$('canvasWrap').style.width=width+'px';$('canvasWrap').style.height=height+'px';const dpr=Math.min(window.devicePixelRatio||1,2);art.width=Math.round(width*dpr);art.height=Math.round(height*dpr);overlay.width=art.width;overlay.height=art.height;draw();}
function draw(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(()=>{renderQueued=false;F.render(art,previewProject||project,{images});drawOverlay();});}
function drawOverlay(){if(previewProject){overlay.getContext('2d').clearRect(0,0,overlay.width,overlay.height);return;}const ctx=overlay.getContext('2d'),scale=overlay.width/project.width;ctx.clearRect(0,0,overlay.width,overlay.height);ctx.save();ctx.scale(scale,scale);ctx.lineWidth=1.5/scale;if(guides){ctx.strokeStyle='#28a07fc0';ctx.setLineDash([5/scale,5/scale]);ctx.strokeRect(project.width*.045,project.height*.045,project.width*.91,project.height*.91);ctx.setLineDash([]);}const o=current();if(o&&o.visible){ctx.save();ctx.translate(o.x+o.w/2,o.y+o.h/2);ctx.rotate(o.rotation*Math.PI/180);ctx.strokeStyle=o.locked?'#bb8a35':'#258a6e';ctx.strokeRect(-o.w/2,-o.h/2,o.w,o.h);if(!o.locked){ctx.fillStyle='white';const size=8/scale;for(const [x,y] of [[-o.w/2,-o.h/2],[o.w/2,-o.h/2],[-o.w/2,o.h/2],[o.w/2,o.h/2]]){ctx.fillRect(x-size/2,y-size/2,size,size);ctx.strokeRect(x-size/2,y-size/2,size,size);}}ctx.restore();}ctx.restore();}
function sync(){window.FlyraSelect.close();loadProjectFonts();if(selected&&!current())selected=null;$('projectName').value=project.name;for(const key of Object.keys(F.defaultContent))$('content-'+key).value=project.content[key];const preset=`${project.width},${project.height}`;if([...$('sizePreset').options].some(o=>o.value===preset))$('sizePreset').value=preset;$('canvasInfo').textContent=`${project.width} × ${project.height} px`;$('layerCount').textContent=project.layers.length;updateUndo();renderLayers();renderProperties();updateTemplateSelection();window.FlyraSelect.enhance();window.FlyraSelect.refresh();fit();}
function select(id){window.FlyraSelect.close();selected=id;renderLayers();renderProperties();window.FlyraSelect.enhance();drawOverlay();}
function renderTemplates(){const list=$('templateList');list.replaceChildren();for(const t of F.templates.filter(t=>filter==='all'||t.category===filter)){const button=document.createElement('button');button.className='template-card';button.dataset.template=t.id;button.setAttribute('aria-label',t.name+' テンプレート');const canvas=document.createElement('canvas');canvas.width=220;canvas.height=275;const p=F.makeProject(t.id,t.preview?{...F.defaultContent,...t.preview}:F.defaultContent);F.render(canvas,p);button.appendChild(canvas);const name=document.createElement('b');name.textContent=t.name;button.appendChild(name);const caption=document.createElement('small');caption.textContent=t.caption;button.appendChild(caption);button.addEventListener('click',()=>{commit(()=>{project=F.applyTemplate(project,t.id,seed());selected=null;});toast(t.name+' を適用しました');});list.appendChild(button);}updateTemplateSelection();}
function updateTemplateSelection(){document.querySelectorAll('.template-card').forEach(b=>{b.classList.toggle('selected',b.dataset.template===project.template);b.setAttribute('aria-pressed',String(b.dataset.template===project.template));b.querySelector('.card-check')?.remove();if(b.dataset.template===project.template){const check=document.createElement('span');check.className='card-check';check.textContent='✓';b.appendChild(check);}});}
function renderLayers(){const list=$('layerList');list.replaceChildren();for(const o of [...project.layers].reverse()){const row=document.createElement('div');row.className='layer-row'+(o.id===selected?' selected':'')+(!o.visible?' hidden-layer':'');const icon=document.createElement('span');icon.className='layer-icon';icon.textContent=o.type==='text'?'T':o.type==='image'?'▧':['particles','grain','halftone'].includes(o.type)?'⁙':'◈';const name=document.createElement('button');name.className='layer-name';name.textContent=o.name;name.title=o.name;name.setAttribute('aria-label','レイヤー '+o.name);name.onclick=()=>select(o.id);const vis=document.createElement('button');vis.className='layer-toggle';vis.textContent=o.visible?'◉':'○';vis.title=o.visible?'非表示にする':'表示する';vis.setAttribute('aria-label',o.name+'の'+vis.title);vis.onclick=()=>commit(()=>o.visible=!o.visible);const lock=document.createElement('button');lock.className='layer-toggle';lock.textContent=o.locked?'▣':'▫';lock.title=o.locked?'ロック解除':'ロックする';lock.setAttribute('aria-label',o.name+'を'+lock.title);lock.onclick=()=>commit(()=>o.locked=!o.locked);row.append(icon,name,vis,lock);list.appendChild(row);}}
function input(label,key,value,type='number',attrs=''){return `<label>${label}<input data-prop="${key}" type="${type}" value="${esc(value)}" ${attrs}></label>`;}
function options(label,key,value,entries){return `<label>${label}<select data-prop="${key}">${entries.map(([v,t])=>`<option value="${esc(v)}" ${String(v)===String(value)?'selected':''}>${t}</option>`).join('')}</select></label>`;}
function range(label,key,value,min,max,step=1){return input(label,key,value,'range',`min="${min}" max="${max}" step="${step}"`);}
function renderProperties(){const o=current(),box=$('properties');$('selectionType').textContent=o?({text:'文字',image:'画像',gradient:'グラデーション',mesh:'メッシュ',grain:'グレイン',particles:'粒子',halftone:'網点'})[o.type]||'図形':'キャンバス';
 if(!o){box.innerHTML=`<div class="empty-selection">要素をクリックして選択。<br>色やサイズを、ここで調整できます。</div>${input('背景色','bgcolor',project.background.color,'color')}<div class="color-swatch-row">${F.palettes.map((p,i)=>`<button class="color-swatch" data-palette="${i}" aria-label="配色 ${i+1}" style="background:${p[2]}"></button>`).join('')}</div><button id="blankCanvas" class="wide">白紙からつくる ＋</button><p class="small-note">変更前のデザインには「元に戻す」で戻れます。</p>`;
 box.querySelector('[data-prop=bgcolor]').onchange=e=>commit(()=>{project.background.type='solid';project.background.color=e.target.value;});box.querySelectorAll('[data-palette]').forEach(b=>b.onclick=()=>commit(()=>F.recolor(project,F.palettes[+b.dataset.palette])));$('blankCanvas').onclick=()=>commit(()=>{project.layers=[];project.background.type='solid';project.background.color='#ffffff';project.template='blank';});return;}
 let html=input('レイヤー名','name',o.name,'text','maxlength="200"');if(o.locked)html+='<p class="lock-notice">▣ ロック中です。編集するには下の鍵を解除。</p>';if(o.slot&&o.type!=='image')html+='<button id="replaceImage" class="primary wide">ここに写真・商品画像を入れる</button>';
 if(o.type==='text'){html+=`<label>テキスト<textarea data-prop="text" rows="3" maxlength="1000">${esc(o.text)}</textarea></label>`;html+=options('書体','font',o.font,F.fontCatalog.map(f=>[f.id,f.label]));html+=`<div class="two-cols">${input('サイズ（上限）','fontSize',Math.round(o.fontSize),'number','min="1" max="2000"')}${options('太さ','fontWeight',o.fontWeight,F.fontWeights(o.font).map(w=>[w,w+' · '+({100:'極細',200:'細め',300:'細字',400:'標準',500:'中太',600:'やや太字',700:'太字',800:'極太',900:'最太'})[w]]))}</div>`;html+='<p id="fontStatus" class="small-note">追加書体は初回にオンラインで読み込みます。英字書体の日本語は標準書体で表示。</p>';html+=options('文字揃え','align',o.align,[['left','左揃え'],['center','中央'],['right','右揃え']]);html+=range('行間','lineHeight',o.lineHeight,.7,3,.05);html+=`<div class="two-cols"><label class="check-label"><input data-prop="outline" type="checkbox" ${o.outline?'checked':''}>輪郭だけ</label><label class="check-label"><input data-prop="shadow" type="checkbox" ${o.shadow?'checked':''}>影をつける</label></div>`;if(F.supportsArc)html+=options('文字の並び','textShape',o.textShape||'normal',[['normal','通常'],['arc','アーチ / 円弧']]);}
 if(o.type!=='image')html+=`<div class="two-cols">${input('カラー','color',o.color,'color')}${input(o.type==='text'?'影の色':'カラー B','color2',o.color2,'color')}</div>`;
 if(['gradient','mesh','particles','grain','halftone'].includes(o.type)){html+=range('角度','angle',o.angle||0,0,360);html+=range('密度','density',o.density||45,5,100);html+='<button id="reseedLayer" class="wide">↻ パターンを作り直す</button>';}
 if(o.type==='image'){html+='<button id="replaceImage" class="wide">画像を差し替える</button>';html+=options('枠への収め方','fit',o.fit,[['cover','枠いっぱいにトリミング'],['contain','画像全体を表示']]);html+=options('切り抜きの形','mask',o.mask,[['rect','四角'],['ellipse','楕円'],...(F.extraMasks||[])]);html+=range('トリミング拡大','cropZoom',o.cropZoom||1,1,4,.05);html+=range('トリミング X','cropX',o.cropX||0,-1,1,.01)+range('トリミング Y','cropY',o.cropY||0,-1,1,.01);html+=range('明るさ','brightness',o.brightness||100,1,200)+range('コントラスト','contrast',o.contrast||100,1,200)+range('モノクロ','grayscale',o.grayscale||0,0,100);if(F.imageEffects){html+=options('印刷の質感','effect',o.effect||'none',F.imageEffects);html+=`<div class="two-cols">${input('暗い色','ink',o.ink||'#202320','color')}${input('明るい色','paper',o.paper||'#f0daab','color')}</div>`;html+=range('網点サイズ','dotSize',o.dotSize||5,2,16)+range('しきい値 / 加工量','effectAmount',o.effectAmount||128,1,255);}}
 html+=`<div class="advanced-divider"></div><div class="two-cols">${input('X','x',Math.round(o.x),'number','min="-20000" max="20000"')}${input('Y','y',Math.round(o.y),'number','min="-20000" max="20000"')}${input('幅','w',Math.round(o.w),'number','min="1" max="20000"')}${input('高さ','h',Math.round(o.h),'number','min="1" max="20000"')}</div>${range('回転','rotation',o.rotation,-180,180)}${range('不透明度','opacity',o.opacity,0,1,.01)}`;
 html+=options('合成モード','blend',o.blend,F.blends);
 html+='<div class="property-actions"><button id="centerX" title="キャンバス左右中央">左右中央</button><button id="centerY" title="キャンバス上下中央">上下中央</button></div><div class="property-actions"><button id="moveUp">前へ ↑</button><button id="moveDown">後ろへ ↓</button></div><div class="property-actions"><button id="duplicateLayer">複製</button><button id="lockLayer">'+(o.locked?'ロック解除':'ロック')+'</button><button id="deleteLayer" class="delete-button">削除</button></div><button id="exportLayer" class="wide">このレイヤーを透過 PNG に ↓</button>';
 box.innerHTML=html;
 box.querySelectorAll('[data-prop]').forEach(el=>{el.disabled=o.locked;el.addEventListener('change',()=>{if(o.locked)return;let value=el.type==='checkbox'?el.checked:el.type==='number'||el.type==='range'||el.dataset.prop==='fontWeight'?Number(el.value):el.value;if(typeof value==='number'){if(!Number.isFinite(value))return;const lo=el.min?Number(el.min):-Infinity,hi=el.max?Number(el.max):Infinity;value=Math.max(lo,Math.min(hi,value));}commit(()=>{o[el.dataset.prop]=value;if(el.dataset.prop==='font')o.fontWeight=F.closestWeight(value,o.fontWeight);if(el.dataset.prop==='text'&&o.role){project.content[o.role]=value;}});});});
 const bind=(id,fn)=>{const b=$(id);if(b){b.disabled=o.locked;b.onclick=fn;}};
 bind('centerX',()=>commit(()=>o.x=(project.width-o.w)/2));bind('centerY',()=>commit(()=>o.y=(project.height-o.h)/2));bind('moveUp',()=>reorder(1));bind('moveDown',()=>reorder(-1));bind('duplicateLayer',duplicate);bind('deleteLayer',remove);bind('reseedLayer',()=>commit(()=>o.seed=seed()));bind('replaceImage',()=>chooseImage(o.id));$('lockLayer').onclick=()=>commit(()=>o.locked=!o.locked);$('exportLayer').onclick=()=>exportImage(true);
}
function reorder(delta){const o=current();if(!o||o.locked)return;const i=project.layers.indexOf(o),j=i+delta;if(j<0||j>=project.layers.length)return;commit(()=>{project.layers.splice(i,1);project.layers.splice(j,0,o);});}
function duplicate(){const o=current();if(!o||o.locked)return;add({...F.clone(o),id:F.uid(),x:o.x+25,y:o.y+25,name:o.name+' のコピー',role:undefined,userAdded:true});}
function remove(){const o=current();if(!o||o.locked)return;commit(()=>{project.layers=project.layers.filter(x=>x.id!==o.id);selected=null;});}
function add(o){if(project.layers.length>=MAX_LAYERS){toast('レイヤーは150個までです');return;}commit(()=>{project.layers.push(o);selected=o.id;});}
function addShape(type){const w=project.width*.3,h=type==='line'?Math.max(3,project.height*.003):project.height*.24;add(F.layer(type,(project.width-w)/2,(project.height-h)/2,w,h,{color:project.palette[2],color2:project.palette[3],name:({rect:'四角',ellipse:'円',triangle:'三角',star:'星',burst:'バースト',line:'ライン',rings:'リング',grid:'グリッド',checker:'市松',chrome:'クローム',arrow:'矢印'})[type]||type,userAdded:true}));}
function material(){return {type:$('materialType').value,color:$('materialColor').value,color2:$('materialColor2').value,angle:+$('materialAngle').value,density:+$('materialDensity').value,seed:materialSeed};}
function previewMaterial(value){const m=material();if(typeof value==='string')m.type=value;$('angleValue').value=m.angle+'°';$('densityValue').value=m.density;const p={width:360,height:270,background:{type:'solid',color:'#000000',color2:'#ffffff'},layers:[F.layer(m.type,0,0,360,270,{...m})]};F.render($('materialPreview'),p,{transparent:true});}
function downloadBlob(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function safeName(){return project.name.replace(/[\\/:*?"<>|]/g,'_')||'FLYRA';}
function png(canvas){return new Promise((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('画像を生成できませんでした')),'image/png'));}
async function exportImage(layerOnly=false){try{await F.ensureProjectFonts(layerOnly?{layers:current()?[current()]:[]}:project);const scale=layerOnly?1:+$('exportScale').value;let p=project,only=current();if(layerOnly&&!only)return;let w=Math.round(p.width*scale),h=Math.round(p.height*scale);if(w*h>40000000){toast('出力が大きすぎます。標準（1倍）を選んでください。');return;}const c=document.createElement('canvas');c.width=w;c.height=h;const format=layerOnly?'png':$('exportFormat').value;F.render(c,p,{images,transparent:layerOnly||format==='png'&&$('transparentExport').checked,onlyLayer:layerOnly?only:null});const blob=await new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(new Error('画像を保存できませんでした')),format==='jpeg'?'image/jpeg':'image/png',.95));downloadBlob(blob,safeName()+(layerOnly?'-layer':'')+'.'+(format==='jpeg'?'jpg':'png'));toast(`${w} × ${h} px で書き出しました`);if(!layerOnly)$('exportDialog').close();}catch(e){toast(e.message);}}
function exportDimensions(){const s=+$('exportScale').value;$('exportDimensions').textContent=`${Math.round(project.width*s)} × ${Math.round(project.height*s)} px`;$('transparentExport').disabled=$('exportFormat').value!=='png';}
let replaceId=null;
function chooseImage(id=null){replaceId=id;$('imageInput').click();}
async function importImage(file,id=null){if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>20*1024*1024){toast('20MB 以下の PNG / JPEG / WebP を選んでください');return;}try{const assetName=await F.resolveAssetName(file,allAssets());const url=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('ファイルを読み込めません'));reader.readAsDataURL(file);});const image=await F.loadImage(url);const c=document.createElement('canvas'),ratio=Math.min(1,2400/Math.max(image.width,image.height));c.width=Math.max(1,Math.round(image.width*ratio));c.height=Math.max(1,Math.round(image.height*ratio));c.getContext('2d').drawImage(image,0,0,c.width,c.height);const src=c.toDataURL('image/png');if(src.length>15000000){toast('画像が大きすぎます。解像度を下げてください。');return;}images.set(src,await F.loadImage(src));const target=project.layers.find(o=>o.id===id);if(target&&!target.locked){commit(()=>{target.type='image';target.src=src;target.fit='cover';target.mask=target.mask||'rect';target.name=assetName;target.userAdded=true;project.layers=project.layers.filter(o=>o.placeholderFor!==target.id);selected=target.id;});}else{const w=project.width*.66,h=Math.min(project.height*.65,w*image.height/image.width);add(F.layer('image',(project.width-w)/2,(project.height-h)/2,w,h,{name:assetName,src,fit:'contain',mask:'rect',brightness:100,contrast:100,grayscale:0,userAdded:true}));}toast('画像を追加しました');}catch(e){toast('画像を読み込めませんでした。別の画像でお試しください。');}}
function point(e){const r=art.getBoundingClientRect();return {x:(e.clientX-r.left)*project.width/r.width,y:(e.clientY-r.top)*project.height/r.height};}
art.addEventListener('pointerdown',e=>{if(e.button!==0)return;art.focus();const p=point(e),o=current(),r=art.getBoundingClientRect(),handle=14*project.width/r.width;let mode='move',target=null;
 if(o&&!o.locked&&o.visible){const q=F.localPoint(o,p.x,p.y);if(Math.abs(q.x-o.w)<handle&&Math.abs(q.y-o.h)<handle){target=o;mode='resize';}}
 if(!target)target=[...project.layers].reverse().find(o=>F.hit(o,p.x,p.y));select(target?.id||null);if(!target)return;drag={start:p,original:F.clone(target),mode,moved:false,before:F.clone(project)};art.setPointerCapture(e.pointerId);
});
art.addEventListener('pointermove',e=>{if(!drag)return;const o=current();if(!o)return;const p=point(e),dx=p.x-drag.start.x,dy=p.y-drag.start.y;drag.moved=drag.moved||Math.abs(dx)+Math.abs(dy)>1;if(drag.mode==='move'){o.x=drag.original.x+dx;o.y=drag.original.y+dy;if(!e.altKey){if(Math.abs(o.x+o.w/2-project.width/2)<7)o.x=(project.width-o.w)/2;if(Math.abs(o.y+o.h/2-project.height/2)<7)o.y=(project.height-o.h)/2;}}else{const a=drag.original.rotation*Math.PI/180,rx=dx*Math.cos(a)+dy*Math.sin(a),ry=-dx*Math.sin(a)+dy*Math.cos(a);let nw=Math.max(10,drag.original.w+rx),nh=Math.max(10,drag.original.h+ry);if(e.shiftKey||o.type==='image'){const ratio=Math.max(nw/drag.original.w,nh/drag.original.h);nw=drag.original.w*ratio;nh=drag.original.h*ratio;}nw=Math.min(nw,20000);nh=Math.min(nh,20000);const dw=nw-drag.original.w,dh=nh-drag.original.h;o.x=drag.original.x+(dw*Math.cos(a)-dh*Math.sin(a)-dw)/2;o.y=drag.original.y+(dw*Math.sin(a)+dh*Math.cos(a)-dh)/2;o.w=nw;o.h=nh;if(o.fontSize)o.fontSize=Math.min(2000,drag.original.fontSize*Math.min(nw/drag.original.w,nh/drag.original.h));}draw();});
function endDrag(){if(!drag)return;if(drag.moved){undoStack.push(drag.before);if(undoStack.length>historyLimit)undoStack.shift();redoStack=[];scheduleSave();}drag=null;sync();}
art.addEventListener('pointerup',endDrag);art.addEventListener('pointercancel',()=>{if(drag){project=drag.before;drag=null;sync();}});art.addEventListener('dblclick',()=>{if(current()?.type==='text')$('properties').querySelector('textarea')?.focus();});
document.addEventListener('keydown',e=>{if(document.activeElement.closest('.preview-menu,.preview-select')||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)||document.querySelector('dialog[open]'))return;const cmd=e.ctrlKey||e.metaKey;if(cmd&&e.key.toLowerCase()==='z'){e.preventDefault();history(e.shiftKey?'redo':'undo');}else if(cmd&&e.key.toLowerCase()==='y'){e.preventDefault();history('redo');}else if(cmd&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate();}else if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();remove();}else if(e.key==='Escape')select(null);else if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key)){const o=current();if(!o||o.locked)return;e.preventDefault();const n=e.shiftKey?10:1;commit(()=>{o.x+=e.key==='ArrowLeft'?-n:e.key==='ArrowRight'?n:0;o.y+=e.key==='ArrowUp'?-n:e.key==='ArrowDown'?n:0;});}});
document.querySelectorAll('[data-panel]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id==='panel-'+b.dataset.panel));if(window.innerWidth<600)$('panel-'+b.dataset.panel).scrollIntoView({behavior:'smooth',block:'start'});});
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderTemplates();});
document.querySelectorAll('[data-shape]').forEach(b=>b.onclick=()=>addShape(b.dataset.shape));
$('addText').onclick=()=>{const w=project.width*.7,h=project.height*.14;add(F.layer('text',project.width*.15,project.height*.43,w,h,{name:'追加テキスト',text:'ここにテキスト',font:'sans',fontWeight:700,fontSize:project.width*.08,lineHeight:1.1,align:'left',color:project.palette[1],userAdded:true}));};
for(const key of Object.keys(F.defaultContent))$('content-'+key).addEventListener('change',e=>{commit(()=>{project.content[key]=e.target.value;project.layers.filter(o=>o.role===key&&!o.locked).forEach(o=>o.text=e.target.value);});if(project.layers.some(o=>o.role===key&&o.locked))toast('ロック中の文字は変更していません');});
$('projectName').onchange=e=>commit(()=>project.name=e.target.value.trim()||'名称未設定');
$('undo').onclick=()=>history('undo');$('redo').onclick=()=>history('redo');
$('sizePreset').onchange=e=>commit(()=>{const [w,h]=e.target.value.split(',').map(Number);F.resizeProject(project,w,h);zoom=1;});
$('toggleGuides').onclick=()=>{guides=!guides;$('toggleGuides').setAttribute('aria-pressed',guides);drawOverlay();};$('zoomIn').onclick=()=>{zoom=Math.min(3,zoom+.2);fit();};$('zoomOut').onclick=()=>{zoom=Math.max(.4,zoom-.2);fit();};$('zoomFit').onclick=()=>{zoom=1;fit();};
$('shufflePalette').onclick=()=>commit(()=>{const candidates=F.palettes.filter(p=>JSON.stringify(p)!==JSON.stringify(project.palette));F.recolor(project,candidates[Math.floor(Math.random()*candidates.length)]);});
$('randomize').onclick=()=>{const candidates=F.templates.filter(t=>t.id!==project.template&&(filter==='all'||t.category===filter));commit(()=>{project=F.applyTemplate(project,candidates[Math.floor(Math.random()*candidates.length)].id,seed());selected=null;});toast('新しい案です。↶ で前の案に戻れます');};
$('shuffleLayout').onclick=()=>commit(()=>{const old=project.palette.slice(),candidates=F.templates.filter(t=>t.id!==project.template&&(filter==='all'||t.category===filter));project=F.applyTemplate(project,candidates[Math.floor(Math.random()*candidates.length)].id,seed());F.recolor(project,old);selected=null;});
for(const id of ['materialType','materialColor','materialColor2','materialAngle','materialDensity'])$(id).addEventListener('input',previewMaterial);
$('materialReseed').onclick=()=>{materialSeed=seed();previewMaterial();};$('addMaterial').onclick=()=>{const m=material();add(F.layer(m.type,project.width*.12,project.height*.18,project.width*.76,project.height*.64,{...m,name:$('materialType').selectedOptions[0].text,userAdded:true}));};
$('setBackground').onclick=()=>commit(()=>project.background=material());
$('materialDownload').onclick=async()=>{try{const m=material(),c=document.createElement('canvas');c.width=1600;c.height=1200;F.render(c,{width:1600,height:1200,layers:[F.layer(m.type,0,0,1600,1200,{...m})]},{transparent:true});downloadBlob(await png(c),'FLYRA-'+m.type+'.png');toast('1600 × 1200 px の素材を保存しました');}catch(e){toast(e.message);}};
$('uploadImage').onclick=()=>chooseImage();$('imageInput').onchange=e=>{const id=replaceId;replaceId=null;importImage(e.target.files[0],id);e.target.value='';};
$('canvasArea').addEventListener('dragover',e=>e.preventDefault());$('canvasArea').addEventListener('drop',async e=>{e.preventDefault();for(const file of [...e.dataTransfer.files].slice(0,10))await importImage(file);});
$('saveProject').onclick=()=>{downloadBlob(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),safeName()+'.flyra');toast('編集データを保存しました');};$('openProject').onclick=()=>$('projectInput').click();$('projectInput').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>50*1024*1024){toast('編集データは50MB 以下にしてください');return;}try{const next=F.validate(JSON.parse(await file.text())),loaded=await F.prepare(next);commit(()=>{project=next;images=loaded;selected=null;zoom=1;});toast('編集データを開きました');}catch(err){toast(err.message||'読み込みに失敗しました');}};
$('export').onclick=()=>{exportDimensions();$('exportDialog').showModal();};$('exportScale').onchange=exportDimensions;$('exportFormat').onchange=exportDimensions;$('downloadExport').onclick=()=>exportImage();$('help').onclick=()=>$('helpDialog').showModal();
function allAssets(){return [...(window.FLYRA_ASSETS||[]),...customAssets];}
function renderAssets(previewFolder){const folder=typeof previewFolder==='string'?previewFolder:$('assetFolder').value,list=$('assetGrid');list.replaceChildren();const assets=allAssets().filter(a=>folder==='mine'?a.custom:a.folder===folder);for(const a of assets){const card=document.createElement('button');card.className='asset-card'+(assetSelection.has(a.id)?' selected':'');card.setAttribute('aria-label',a.name+' 素材を選択');card.setAttribute('aria-pressed',String(assetSelection.has(a.id)));const image=document.createElement('img');image.src=a.src;image.alt='';image.loading='lazy';const name=document.createElement('span');name.textContent=a.name;const tag=document.createElement('small');tag.textContent=a.custom?'MY ASSET':'AI ORIGINAL';card.append(image,name,tag);card.onclick=()=>{assetSelection.has(a.id)?assetSelection.delete(a.id):assetSelection.add(a.id);renderAssets();};list.appendChild(card);}if(!assets.length){const p=document.createElement('p');p.className='small-note';p.textContent='画像やフォルダを登録すると、ここに並びます。';list.appendChild(p);}const count=assetSelection.size;$('addSelectedAssets').disabled=!count;$('addSelectedAssets').textContent=count?`選択した ${count} 点を追加 ＋`:'選択した素材を追加';}
async function storeAssets(){if(!db){toast('素材棚の自動保存が使えません。「素材棚を保存」で残してください');return;}await new Promise((resolve,reject)=>{const tx=db.transaction('assets','readwrite');tx.objectStore('assets').put(customAssets,'library');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
async function readAsset(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>20*1024*1024)throw new Error(file.name+'：対応形式・サイズ外');const src=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});const im=await F.loadImage(src),c=document.createElement('canvas'),ratio=Math.min(1,2400/Math.max(im.width,im.height));c.width=Math.round(im.width*ratio);c.height=Math.round(im.height*ratio);c.getContext('2d').drawImage(im,0,0,c.width,c.height);const result=c.toDataURL('image/png');if(result.length>15000000)throw new Error('解像度が大きすぎます');return result;}
async function registerAssets(files){const accepted=[...files].filter(f=>['image/png','image/jpeg','image/webp'].includes(f.type));if(customAssets.length+accepted.length>100){toast('素材棚への登録は100点までです');return;}const folder=$('assetFolder').value==='mine'?'icons':$('assetFolder').value;let count=0;for(const file of accepted){try{const name=await F.resolveAssetName(file,allAssets());const src=await readAsset(file);customAssets.push({id:F.uid(),name:name.slice(0,160),folder,src,custom:true,blend:folder==='textures'?'overlay':'source-over',opacity:1});count++;}catch(e){toast(e.message||'画像を登録できませんでした');}}try{await storeAssets();}catch{toast('自動保存できませんでした。「素材棚を保存」を使ってください');}renderAssets();toast(count?`${count} 点を素材棚に登録しました`:'PNG / JPEG / WebP が見つかりませんでした');}
$('assetFolder').onchange=()=>{assetSelection.clear();renderAssets();};$('importAssets').onclick=()=>$('assetsInput').click();$('importAssetFolder').onclick=()=>$('assetFolderInput').click();for(const id of ['assetsInput','assetFolderInput'])$(id).onchange=async e=>{await registerAssets(e.target.files);e.target.value='';};
$('addSelectedAssets').onclick=async()=>{const assets=allAssets().filter(a=>assetSelection.has(a.id));if(project.layers.length+assets.length>MAX_LAYERS){toast('レイヤーは150個までです');return;}try{const layers=[];for(const a of assets){const im=await F.loadImage(a.src);images.set(a.src,im);const texture=a.folder==='textures',w=texture?project.width:project.width*.35,h=texture?project.height:w*im.height/im.width;layers.push(F.layer('image',texture?0:(project.width-w)/2+layers.length*18,texture?0:(project.height-h)/2+layers.length*18,w,h,{name:a.name,src:a.src,fit:texture?'cover':'contain',mask:'rect',brightness:100,contrast:100,grayscale:0,blend:a.blend||'source-over',opacity:a.opacity??1,userAdded:true}));}commit(()=>{project.layers.push(...layers);selected=layers.at(-1)?.id;});assetSelection.clear();renderAssets();toast(`${layers.length} 点の素材を追加しました`);}catch(e){toast('素材の読み込みに失敗しました');}};
$('saveAssetLibrary').onclick=()=>{downloadBlob(new Blob([JSON.stringify({format:'flyra-assets',version:1,assets:customAssets})],{type:'application/json'}),'FLYRA-my-assets.json');toast('自分で登録した素材を保存しました');};$('loadAssetLibrary').onclick=()=>$('assetLibraryInput').click();$('assetLibraryInput').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>150*1024*1024){toast('素材棚ファイルは150MBまでです');return;}try{const data=JSON.parse(await file.text());if(data.format!=='flyra-assets'||data.version!==1||!Array.isArray(data.assets)||data.assets.length>100)throw Error();const incoming=[];for(const a of data.assets){if(!a||typeof a.name!=='string'||a.name.length>160||!['textures','icons'].includes(a.folder)||typeof a.src!=='string'||a.src.length>15000000||!/^data:image\/(png|jpeg|webp);base64,[a-z0-9+/=]+$/i.test(a.src))throw Error();await F.loadImage(a.src);incoming.push({id:F.uid(),name:a.name,folder:a.folder,src:a.src,custom:true,blend:a.folder==='textures'?'overlay':'source-over',opacity:1});}if(customAssets.length+incoming.length>100){toast('登録済み素材と合わせて100点を超えます');return;}customAssets.push(...incoming);await storeAssets();$('assetFolder').value='mine';renderAssets();toast(`${incoming.length} 点を素材棚に読み込みました`);}catch{toast('素材棚ファイルを読み込めませんでした');}};

// Preview a separate render snapshot. Saved project and undo history never change.
document.addEventListener('optionpreview',e=>{
 const el=e.target,value=e.detail.value;
 if(el.dataset.prop){const o=current();if(!o||o.locked)return;previewProject={...project,layers:project.layers.map(x=>x.id===o.id?{...x,[el.dataset.prop]:el.dataset.prop==='fontWeight'?Number(value):value,...(el.dataset.prop==='font'?{fontWeight:F.closestWeight(value,o.fontWeight)}:{})}:x)};draw();const snapshot=previewProject;F.ensureProjectFonts(snapshot).then(()=>{if(previewProject===snapshot)draw();}).catch(()=>{if(previewProject===snapshot)toast('この書体はネット接続が必要です');});}
 else if(el.id==='materialType')previewMaterial(value);
 else if(el.id==='assetFolder')renderAssets(value);
 else if(el.id==='sizePreset'){previewProject=F.clone(project);const [w,h]=value.split(',').map(Number);F.resizeProject(previewProject,w,h);$('canvasInfo').textContent=w+' × '+h+' px · プレビュー';const area=$('canvasArea'),scale=Math.min((area.clientWidth-68)/w,(area.clientHeight-68)/h)*zoom;const dpr=Math.min(window.devicePixelRatio||1,2);$('canvasWrap').style.width=Math.max(40,w*scale)+'px';$('canvasWrap').style.height=Math.max(40,h*scale)+'px';art.width=Math.round(Math.max(40,w*scale)*dpr);art.height=Math.round(Math.max(40,h*scale)*dpr);overlay.width=art.width;overlay.height=art.height;draw();}
 else if(el.id==='exportScale')$('exportDimensions').textContent=Math.round(project.width*Number(value))+' × '+Math.round(project.height*Number(value))+' px · プレビュー';
 else if(el.id==='exportFormat')$('exportDimensions').textContent=(value==='jpeg'?'JPEG · 背景付き':'PNG · 透過に対応')+' · プレビュー';
});
document.addEventListener('previewcancel',e=>{previewProject=null;if(e.target.id==='materialType')previewMaterial();else if(e.target.id==='assetFolder')renderAssets();else if(e.target.id==='sizePreset'){$('canvasInfo').textContent=project.width+' × '+project.height+' px';fit();}else if(e.target.id.startsWith('export'))exportDimensions();draw();});
new ResizeObserver(fit).observe($('canvasArea'));
async function init(){await initStorage();renderTemplates();renderAssets();previewMaterial();sync();}
init().catch(e=>{toast('起動に失敗しました。ページを再読み込みしてください。');console.error(e);});
})();


