/* Original image processing, alpha-correct blend modes and procedural decorations. */
(() => {
'use strict';const F=window.Flyra;
F.supportsArc=true;F.extraMasks=[['blob','ゆらぐ切り抜き'],['double','双眼鏡 / ダブル円'],['diamond','ひし形']];
F.imageEffects=[['none','なし'],['duotone','デュオトーン / 二色'],['threshold','二階調 / シルクスクリーン'],['halftone','ハーフトーン / 網点'],['slice','スライス / ゆがみ']];
F.blends=[['source-over','通常'],['multiply','乗算'],['screen','スクリーン'],['overlay','オーバーレイ'],['soft-light','ソフトライト'],['hard-light','ハードライト'],['hard-mix','ハードミックス'],['color-dodge','覆い焼きカラー'],['color-burn','焼き込みカラー'],['darken','比較（暗）'],['lighten','比較（明）'],['difference','差の絶対値'],['exclusion','除外'],['hue','色相'],['saturation','彩度'],['color','カラー'],['luminosity','輝度'],['lighter','加算']];
const originalDraw=F.drawLayer,cache=new Map(),imageIds=new WeakMap();let nextImageId=0;
const newCanvas=(w,h)=>{const c=document.createElement('canvas');c.width=Math.max(1,Math.round(w));c.height=Math.max(1,Math.round(h));return c;};
const rgb=c=>[parseInt(c.slice(1,3),16),parseInt(c.slice(3,5),16),parseInt(c.slice(5,7),16)];
function processedImage(o,image){const ratio=Math.min(1,1600/Math.max(image.width,image.height)),w=Math.round(image.width*ratio),h=Math.round(image.height*ratio);if(!imageIds.has(image))imageIds.set(image,++nextImageId);const key=JSON.stringify([imageIds.get(image),o.effect,o.ink,o.paper,o.dotSize,o.effectAmount]);if(cache.has(key))return cache.get(key);let canvas=newCanvas(w,h),ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(image,0,0,w,h);const pixels=ctx.getImageData(0,0,w,h),d=pixels.data,ink=rgb(o.ink||'#202320'),paper=rgb(o.paper||'#f0daab');
 if(o.effect==='duotone'||o.effect==='threshold'){for(let i=0;i<d.length;i+=4){let v=(d[i]*.2126+d[i+1]*.7152+d[i+2]*.0722)/255;if(o.effect==='threshold')v=v*255>(o.effectAmount||128)?1:0;for(let k=0;k<3;k++)d[i+k]=Math.round(ink[k]*(1-v)+paper[k]*v);}ctx.putImageData(pixels,0,0);}
 else if(o.effect==='halftone'){ctx.clearRect(0,0,w,h);ctx.fillStyle=o.paper||'#f0daab';ctx.fillRect(0,0,w,h);ctx.fillStyle=o.ink||'#202320';const step=(o.dotSize||5)*w/650;for(let y=step/2;y<h;y+=step)for(let x=step/2;x<w;x+=step){const i=(Math.min(h-1,Math.floor(y))*w+Math.min(w-1,Math.floor(x)))*4;const v=(d[i]*.2126+d[i+1]*.7152+d[i+2]*.0722)/255;ctx.beginPath();ctx.arc(x,y,Math.sqrt(1-v)*step*.57,0,Math.PI*2);ctx.fill();}const alpha=newCanvas(w,h),ac=alpha.getContext('2d');ac.putImageData(pixels,0,0);ctx.globalCompositeOperation='destination-in';ctx.drawImage(alpha,0,0);ctx.globalCompositeOperation='source-over';}
 else if(o.effect==='slice'){const out=newCanvas(w,h),oc=out.getContext('2d'),slice=Math.max(2,Math.round(w/60)),amount=(o.effectAmount||128)/255;for(let x=0;x<w;x+=slice){const offset=Math.sin(x/w*18)*h*.15*amount;oc.drawImage(canvas,x,0,Math.min(slice,w-x),h,x,offset,Math.min(slice,w-x),h);}canvas=out;}
 cache.set(key,canvas);if(cache.size>12)cache.delete(cache.keys().next().value);return canvas;}
function maskPath(ctx,o){const w=o.w,h=o.h;ctx.beginPath();if(F.extraMaskPaths?.[o.mask]){F.extraMaskPaths[o.mask](ctx,w,h);return;}if(o.mask==='ellipse')ctx.ellipse(w/2,h/2,w/2,h/2,0,0,Math.PI*2);else if(o.mask==='diamond'){ctx.moveTo(w/2,0);ctx.lineTo(w,h/2);ctx.lineTo(w/2,h);ctx.lineTo(0,h/2);ctx.closePath();}else if(o.mask==='double'){ctx.ellipse(w*.29,h*.5,w*.29,h*.5,0,0,Math.PI*2);ctx.moveTo(w,h*.5);ctx.ellipse(w*.71,h*.5,w*.29,h*.5,0,0,Math.PI*2);}else if(o.mask==='blob'){ctx.moveTo(w*.25,0);ctx.bezierCurveTo(w*.5,h*.13,w*.8,-h*.1,w*.97,h*.15);ctx.bezierCurveTo(w*1.1,h*.5,w*.7,h*.5,w*.96,h*.8);ctx.bezierCurveTo(w*.7,h*1.14,w*.48,h*.84,w*.15,h);ctx.bezierCurveTo(-w*.2,h*.86,w*.18,h*.6,w*.03,h*.35);ctx.bezierCurveTo(-w*.1,h*.12,w*.16,h*.18,w*.25,0);ctx.closePath();}else ctx.rect(0,0,w,h);}
F.maskPath=maskPath;
F.drawLayer=(ctx,o,images=new Map())=>{
 if(!o.visible)return;
 if(o.type==='image'&&(o.effect&&o.effect!=='none'||!['rect','ellipse'].includes(o.mask))){const im=images.get(o.src);if(!im)return;const processed=o.effect&&o.effect!=='none'?processedImage(o,im):im;ctx.save();ctx.globalAlpha=o.opacity;ctx.globalCompositeOperation=o.blend;ctx.translate(o.x+o.w/2,o.y+o.h/2);ctx.rotate(o.rotation*Math.PI/180);ctx.translate(-o.w/2,-o.h/2);maskPath(ctx,o);ctx.clip();ctx.filter=`brightness(${o.brightness||100}%) contrast(${o.contrast||100}%) grayscale(${o.grayscale||0}%)`;const ratio=(o.fit==='contain'?Math.min:Math.max)(o.w/processed.width,o.h/processed.height)*(o.cropZoom||1),w=processed.width*ratio,h=processed.height*ratio;ctx.drawImage(processed,(o.w-w)/2+(o.cropX||0)*Math.abs(o.w-w)/2,(o.h-h)/2+(o.cropY||0)*Math.abs(o.h-h)/2,w,h);ctx.restore();return;}
 if(o.type==='text'&&o.textShape==='arc'){ctx.save();ctx.globalAlpha=o.opacity;ctx.globalCompositeOperation=o.blend;ctx.translate(o.x+o.w/2,o.y+o.h/2);ctx.rotate(o.rotation*Math.PI/180);ctx.fillStyle=F.paint?F.paint(ctx,o):o.color;ctx.strokeStyle=F.paint?F.paint(ctx,o):o.color;let size=Math.min(o.fontSize,o.h*.5);ctx.font=`${F.nativeTextWeight?F.nativeTextWeight(o):o.fontWeight} ${size}px ${F.fonts[o.font]}`;const chars=Array.from(o.text.replace(/\n/g,' ')),total=ctx.measureText(chars.join('')).width,r=Math.max(o.w*.38,total/Math.PI),spread=Math.min(Math.PI*.92,total/r);let a=-spread/2;ctx.textAlign='center';ctx.textBaseline='middle';chars.forEach(ch=>{const advance=ctx.measureText(ch).width/r;ctx.save();ctx.translate(Math.sin(a+advance/2)*r,-Math.cos(a+advance/2)*r+r*.55);ctx.rotate(a+advance/2);F.paintText?F.paintText(ctx,o,ch,0,0):o.outline?ctx.strokeText(ch,0,0):ctx.fillText(ch,0,0);ctx.restore();a+=advance;});ctx.restore();return;}
 if(['checker','chrome','arrow'].includes(o.type)){ctx.save();ctx.globalAlpha=o.opacity;ctx.globalCompositeOperation=o.blend;ctx.translate(o.x+o.w/2,o.y+o.h/2);ctx.rotate(o.rotation*Math.PI/180);ctx.translate(-o.w/2,-o.h/2);ctx.fillStyle=F.paint?F.paint(ctx,o):o.color;const w=o.w,h=o.h;if(o.type==='checker'){const n=10,m=5;for(let x=0;x<n;x++)for(let y=0;y<m;y++)if((x+y)%2===0)ctx.fillRect(x*w/n,y*h/m,w/n,h/m);}else if(o.type==='arrow'){ctx.beginPath();ctx.moveTo(0,h*.35);ctx.lineTo(w*.63,h*.35);ctx.lineTo(w*.63,0);ctx.lineTo(w,h*.5);ctx.lineTo(w*.63,h);ctx.lineTo(w*.63,h*.65);ctx.lineTo(0,h*.65);ctx.closePath();ctx.fill();}else{const g=ctx.createLinearGradient(0,0,w,h);['#121c53','#e7f7ff','#6970b2','#ffffff','#353172','#d3e7ff','#10113a'].forEach((c,i)=>g.addColorStop(i/6,c));ctx.strokeStyle=g;ctx.lineWidth=w*.033;for(let i=0;i<17;i++){ctx.beginPath();ctx.ellipse(w/2,h/2,w*(.12+i*.021),h*(.07+i*.025),i*.21,0,Math.PI*2);ctx.stroke();}}ctx.restore();return;}
 originalDraw(ctx,o,images);
};
const originalRender=F.render;
// Hard Mix is not a Canvas compositing keyword. Blend straight-alpha channels
// explicitly, using the binary result of Vivid Light, then Porter-Duff source-over.
F.hardMixChannel=(back,front)=>back+front>=255?255:0;
F.hardMixPixels=(back,front,opacity)=>{for(let i=0;i<back.length;i+=4){const ab=back[i+3]/255,as=front[i+3]/255*opacity,ao=as+ab*(1-as);if(!ao)continue;for(let k=0;k<3;k++){const cb=back[i+k],cs=front[i+k],blend=F.hardMixChannel(cb,cs);back[i+k]=Math.round(((1-as)*ab*cb+(1-ab)*as*cs+ab*as*blend)/ao);}back[i+3]=Math.round(ao*255);}return back;};
F.render=(canvas,p,opts={})=>{const visible=opts.onlyLayer?[opts.onlyLayer]:p.layers;if(!visible.some(o=>o.visible&&o.blend==='hard-mix'))return originalRender(canvas,p,opts);const base={...p,layers:[]};originalRender(canvas,base,{...opts,onlyLayer:null,transparent:opts.transparent||!!opts.onlyLayer});const ctx=canvas.getContext('2d',{willReadFrequently:true});let temp;
 for(const o of visible){if(!o.visible)continue;if(o.blend!=='hard-mix'){ctx.save();ctx.scale(canvas.width/p.width,canvas.height/p.height);F.drawLayer(ctx,o,opts.images);ctx.restore();continue;}temp=temp||newCanvas(canvas.width,canvas.height);const copy={...o,blend:'source-over',opacity:1};originalRender(temp,{...p,layers:[copy]},{...opts,onlyLayer:null,transparent:true});const b=ctx.getImageData(0,0,canvas.width,canvas.height),s=temp.getContext('2d').getImageData(0,0,temp.width,temp.height);F.hardMixPixels(b.data,s.data,o.opacity);ctx.putImageData(b,0,0);}
};
const originalValidate=F.validate;
F.validate=p=>{const copy=F.clone(p);const patched=F.clone(p);for(const o of patched.layers||[]){if(!F.blends.some(([v])=>v===o.blend))throw new Error('未対応の合成モードです');if(['checker','chrome','arrow'].includes(o.type))o.type='rect';if(o.type==='image'){if(!['rect','ellipse',...F.extraMasks.map(x=>x[0])].includes(o.mask))throw new Error('未対応の切り抜きです');o.mask='rect';if(o.effect&&!F.imageEffects.some(([v])=>v===o.effect))throw new Error('未対応の画像加工です');for(const key of ['ink','paper'])if(o[key]&&!/^#[0-9a-f]{6}$/i.test(o[key]))throw new Error('画像の色が不正です');for(const [k,a,b] of [['dotSize',2,16],['effectAmount',1,255]])if(o[k]!==undefined&&(!Number.isFinite(o[k])||o[k]<a||o[k]>b))throw new Error('画像の加工値が不正です');}o.blend='source-over';}originalValidate(patched);return copy;};
})();
